-- Purchase FMS demo seed — generated by frontend/scripts/seed-fms-demo.mjs
-- 26 dummy entries (PO-2001..PO-2026). Remove with fms_demo_teardown.sql.
\set ON_ERROR_STOP on
BEGIN;
SELECT id AS wf FROM public.fms_workflows WHERE key='purchase' \gset
SELECT id AS creator FROM auth.users WHERE email='master@taskflow.app' \gset

-- PO-2001  (active step 9)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2001', $j${"category":"PACKING MATERIAL","itemName":"Carton Sealing Tape","quantity":275,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-20T09:03:00Z', 9, 'completed')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-20', actual_date='2026-05-20T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"Carton Sealing Tape","quantity":275,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-21', actual_date='2026-05-21T11:17:00Z', values=$j${"status":"Approved","vendorName":"Nexus Polymers","finalQty":275,"finalRate":2120,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-22', actual_date='2026-05-23T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3000","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-25', actual_date='2026-05-24T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5500","materialDispatchDate":"2026-05-29","paymentTerms":"Credit","totalGstValue":687940,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-26', actual_date='2026-05-26T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Credit)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-28', actual_date='2026-05-28T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40000","transportDetails":"TCI Express","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-05-30T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1200","receivedQty":275,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-05-31T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/800","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-03T12:24:00Z', values=$j${"dueDate":"2026-06-05","pendingAmount":275176,"datePaid":"2026-06-03"}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=8;

-- PO-2002  (active step 9)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2002', $j${"category":"PACKING MATERIAL","itemName":"Shrink Film Rolls","quantity":475,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-21T09:03:00Z', 9, 'completed')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-21', actual_date='2026-05-21T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"Shrink Film Rolls","quantity":475,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-22', actual_date='2026-05-22T11:17:00Z', values=$j${"status":"Approved","vendorName":"Global Filtration Co","finalQty":475,"finalRate":1270,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-23', actual_date='2026-05-23T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3001","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-25', actual_date='2026-05-24T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5501","materialDispatchDate":"2026-05-30","paymentTerms":"On Delivery","totalGstValue":711835,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-26', actual_date='2026-05-26T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (On Delivery)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-29', actual_date='2026-05-28T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40007","transportDetails":"VRL Logistics","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-05-31T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1201","receivedQty":475,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-06-01T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/801","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T12:24:00Z', values=$j${"dueDate":"2026-06-06","pendingAmount":284734,"datePaid":"2026-06-04"}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=8;

-- PO-2003  (active step 9)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2003', $j${"category":"CARTRIDGE/FILTER","itemName":"Bag Filter PP #2","quantity":200,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-20T09:03:00Z', 9, 'completed')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-20', actual_date='2026-05-20T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"Bag Filter PP #2","quantity":200,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-21', actual_date='2026-05-21T11:17:00Z', values=$j${"status":"Approved","vendorName":"Orient Chem Agencies","finalQty":200,"finalRate":420,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-22', actual_date='2026-05-22T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3002","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-23', actual_date='2026-05-25T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5502","materialDispatchDate":"2026-05-31","paymentTerms":"Credit","totalGstValue":99120,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-27', actual_date='2026-05-27T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Credit)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-05-29T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40014","transportDetails":"VRL Logistics","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-05-31T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1202","receivedQty":200,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-06-01T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/802","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-06T12:24:00Z', values=$j${"dueDate":"2026-06-06","pendingAmount":39648,"datePaid":"2026-06-06"}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=8;

-- PO-2004  (active step 9)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2004', $j${"category":"CARTRIDGE/FILTER","itemName":"Pleated Filter Cartridge","quantity":400,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-26T09:03:00Z', 9, 'completed')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-26', actual_date='2026-05-26T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"Pleated Filter Cartridge","quantity":400,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-27', actual_date='2026-05-27T11:17:00Z', values=$j${"status":"Approved","vendorName":"Sunrise Industrial","finalQty":400,"finalRate":1980,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-28', actual_date='2026-05-28T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3003","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-29', actual_date='2026-05-29T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5503","materialDispatchDate":"2026-06-03","paymentTerms":"On Delivery","totalGstValue":934560,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-05-31T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (On Delivery)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-02T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40021","transportDetails":"Delhivery Cargo","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1203","receivedQty":400,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-05', actual_date='2026-06-05T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/803","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-09', actual_date='2026-06-08T12:24:00Z', values=$j${"dueDate":"2026-06-10","pendingAmount":373824,"datePaid":"2026-06-08"}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=8;

-- PO-2005  (active step 9)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2005', $j${"category":"CARTRIDGE/FILTER","itemName":"Carbon Block Cartridge","quantity":100,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-23T09:03:00Z', 9, 'completed')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-23', actual_date='2026-05-23T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"Carbon Block Cartridge","quantity":100,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-25', actual_date='2026-05-24T11:17:00Z', values=$j${"status":"Approved","vendorName":"Apex Materials Pvt Ltd","finalQty":100,"finalRate":1130,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-25', actual_date='2026-05-25T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3004","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-26', actual_date='2026-05-26T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5504","materialDispatchDate":"2026-05-31","paymentTerms":"Credit","totalGstValue":133340,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-28', actual_date='2026-05-28T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Credit)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-05-30T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40028","transportDetails":"Safexpress","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-01T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1204","receivedQty":100,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-04T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/804","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-07T12:24:00Z', values=$j${"dueDate":"2026-06-09","pendingAmount":53336,"datePaid":"2026-06-07"}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=8;

-- PO-2006  (active step 9)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2006', $j${"category":"CARTRIDGE/FILTER","itemName":"AC Carbon Cartridge","quantity":325,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-15T09:03:00Z', 9, 'completed')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-15', actual_date='2026-05-15T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"AC Carbon Cartridge","quantity":325,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-16', actual_date='2026-05-18T11:17:00Z', values=$j${"status":"Approved","vendorName":"Nexus Polymers","finalQty":325,"finalRate":280,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-19', actual_date='2026-05-19T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3005","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-20', actual_date='2026-05-20T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5505","materialDispatchDate":"2026-05-25","paymentTerms":"On Delivery","totalGstValue":107380,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-22', actual_date='2026-05-22T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (On Delivery)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-23', actual_date='2026-05-24T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40035","transportDetails":"Gati Ltd","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-26', actual_date='2026-05-26T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1205","receivedQty":325,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-27', actual_date='2026-05-29T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/805","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-03T12:24:00Z', values=$j${"dueDate":"2026-06-03","pendingAmount":42952,"datePaid":"2026-06-03"}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=8;

-- PO-2007  (active step 1)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2007', $j${"category":"CARTRIDGE/FILTER","itemName":"Micron Filter 5um","quantity":25,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-10T09:03:00Z', 1, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"Micron Filter 5um","quantity":25,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=1;

-- PO-2008  (active step 1)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2008', $j${"category":"CARTRIDGE/FILTER","itemName":"Bag Filter PP #2","quantity":225,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-10T09:03:00Z', 1, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"Bag Filter PP #2","quantity":225,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=1;

-- PO-2009  (active step 1, overdue)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2009', $j${"category":"CARTRIDGE/FILTER","itemName":"RO Membrane 4040","quantity":450,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-04T09:03:00Z', 1, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"RO Membrane 4040","quantity":450,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-05' WHERE entry_id=:'e' AND step_index=1;

-- PO-2010  (active step 2)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2010', $j${"category":"CARTRIDGE/FILTER","itemName":"Carbon Block Cartridge","quantity":150,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-09T09:03:00Z', 2, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-09', actual_date='2026-06-09T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"Carbon Block Cartridge","quantity":150,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T11:17:00Z', values=$j${"status":"Approved","vendorName":"Pinnacle Traders","finalQty":150,"finalRate":1700,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=2;

-- PO-2011  (active step 2)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2011', $j${"category":"CARTRIDGE/FILTER","itemName":"AC Carbon Cartridge","quantity":350,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-09T09:03:00Z', 2, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-09', actual_date='2026-06-09T10:10:00Z', values=$j${"category":"CARTRIDGE/FILTER","itemName":"AC Carbon Cartridge","quantity":350,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T11:17:00Z', values=$j${"status":"Approved","vendorName":"Meridian Supplies","finalQty":350,"finalRate":850,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=2;

-- PO-2012  (active step 3)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2012', $j${"category":"RAW MATERIAL","itemName":"Zinc Sulphate","quantity":75,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-07T09:03:00Z', 3, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-07', actual_date='2026-06-07T10:10:00Z', values=$j${"category":"RAW MATERIAL","itemName":"Zinc Sulphate","quantity":75,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-08T11:17:00Z', values=$j${"status":"Approved","vendorName":"Shree Chemicals","finalQty":75,"finalRate":2400,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-09', actual_date='2026-06-10T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3011","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=3;

-- PO-2013  (active step 3)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2013', $j${"category":"RAW MATERIAL","itemName":"Calcium Carbonate","quantity":275,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-07T09:03:00Z', 3, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-07', actual_date='2026-06-07T10:10:00Z', values=$j${"category":"RAW MATERIAL","itemName":"Calcium Carbonate","quantity":275,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-09T11:17:00Z', values=$j${"status":"Approved","vendorName":"Veer Enterprises","finalQty":275,"finalRate":1560,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3012","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=3;

-- PO-2014  (active step 3, overdue)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2014', $j${"category":"RAW MATERIAL","itemName":"Activated Carbon Granules","quantity":475,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-31T09:03:00Z', 3, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-31', actual_date='2026-05-31T10:10:00Z', values=$j${"category":"RAW MATERIAL","itemName":"Activated Carbon Granules","quantity":475,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-06-03T11:17:00Z', values=$j${"status":"Approved","vendorName":"Krishna Packaging","finalQty":475,"finalRate":710,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3013","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-05' WHERE entry_id=:'e' AND step_index=3;

-- PO-2015  (active step 4)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2015', $j${"category":"RAW MATERIAL","itemName":"Titanium Dioxide","quantity":200,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-06T09:03:00Z', 4, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-06', actual_date='2026-06-06T10:10:00Z', values=$j${"category":"RAW MATERIAL","itemName":"Titanium Dioxide","quantity":200,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-07T11:17:00Z', values=$j${"status":"Approved","vendorName":"Pinnacle Traders","finalQty":200,"finalRate":2260,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-09T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3014","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5514","materialDispatchDate":"2026-06-15","paymentTerms":"Partial Advance","totalGstValue":533360,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-12' WHERE entry_id=:'e' AND step_index=4;

-- PO-2016  (active step 4, overdue)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2016', $j${"category":"RAW MATERIAL","itemName":"Copper Sulphate","quantity":400,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-31T09:03:00Z', 4, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-31', actual_date='2026-05-31T10:10:00Z', values=$j${"category":"RAW MATERIAL","itemName":"Copper Sulphate","quantity":400,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-06-01T11:17:00Z', values=$j${"status":"Approved","vendorName":"Meridian Supplies","finalQty":400,"finalRate":1420,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-02T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3015","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-03T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5515","materialDispatchDate":"2026-06-09","paymentTerms":"Credit","totalGstValue":670240,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-05' WHERE entry_id=:'e' AND step_index=4;

-- PO-2017  (active step 5)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2017', $j${"category":"RAW MATERIAL","itemName":"Zinc Sulphate","quantity":100,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-03T09:03:00Z', 5, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-03T10:10:00Z', values=$j${"category":"RAW MATERIAL","itemName":"Zinc Sulphate","quantity":100,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T11:17:00Z', values=$j${"status":"Approved","vendorName":"Shree Chemicals","finalQty":100,"finalRate":570,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-05', actual_date='2026-06-05T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3016","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-06', actual_date='2026-06-08T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5516","materialDispatchDate":"2026-06-13","paymentTerms":"On Delivery","totalGstValue":67260,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (On Delivery)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-12' WHERE entry_id=:'e' AND step_index=5;

-- PO-2018  (active step 5)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2018', $j${"category":"RAW MATERIAL","itemName":"Calcium Carbonate","quantity":325,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-03T09:03:00Z', 5, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-03T10:10:00Z', values=$j${"category":"RAW MATERIAL","itemName":"Calcium Carbonate","quantity":325,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T11:17:00Z', values=$j${"status":"Approved","vendorName":"Veer Enterprises","finalQty":325,"finalRate":2120,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-05', actual_date='2026-06-07T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3017","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-08T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5517","materialDispatchDate":"2026-06-12","paymentTerms":"Credit","totalGstValue":813020,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Credit)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=5;

-- PO-2019  (active step 6)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2019', $j${"category":"RAW MATERIAL","itemName":"Activated Carbon Granules","quantity":25,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-02T09:03:00Z', 6, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-02T10:10:00Z', values=$j${"category":"RAW MATERIAL","itemName":"Activated Carbon Granules","quantity":25,"unit":"KGS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-03T11:17:00Z', values=$j${"status":"Approved","vendorName":"Krishna Packaging","finalQty":25,"finalRate":1280,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3018","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-05', actual_date='2026-06-05T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5518","materialDispatchDate":"2026-06-10","paymentTerms":"On Delivery","totalGstValue":37760,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-07T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (On Delivery)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-09', actual_date='2026-06-10T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40126","transportDetails":"Delhivery Cargo","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-12' WHERE entry_id=:'e' AND step_index=6;

-- PO-2020  (active step 6)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2020', $j${"category":"PACKING MATERIAL","itemName":"HDPE Drums 50L","quantity":225,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-06-03T09:03:00Z', 6, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-03T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"HDPE Drums 50L","quantity":225,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T11:17:00Z', values=$j${"status":"Approved","vendorName":"Pinnacle Traders","finalQty":225,"finalRate":430,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-05', actual_date='2026-06-05T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3019","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-06', actual_date='2026-06-06T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5519","materialDispatchDate":"2026-06-12","paymentTerms":"Credit","totalGstValue":114165,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-09', actual_date='2026-06-08T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Credit)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-11', actual_date='2026-06-10T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40133","transportDetails":"Safexpress","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-12' WHERE entry_id=:'e' AND step_index=6;

-- PO-2021  (active step 6, overdue)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2021', $j${"category":"PACKING MATERIAL","itemName":"Carton Sealing Tape","quantity":450,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-22T09:03:00Z', 6, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-22', actual_date='2026-05-22T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"Carton Sealing Tape","quantity":450,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-23', actual_date='2026-05-24T11:17:00Z', values=$j${"status":"Approved","vendorName":"Sunrise Industrial","finalQty":450,"finalRate":1980,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-25', actual_date='2026-05-25T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3020","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-26', actual_date='2026-05-26T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5520","materialDispatchDate":"2026-06-01","paymentTerms":"On Delivery","totalGstValue":1051380,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-28', actual_date='2026-05-30T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (On Delivery)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-06-02T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40140","transportDetails":"Gati Ltd","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-04' WHERE entry_id=:'e' AND step_index=6;

-- PO-2022  (active step 7)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2022', $j${"category":"PACKING MATERIAL","itemName":"PP Woven Bags","quantity":150,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-30T09:03:00Z', 7, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-05-30T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"PP Woven Bags","quantity":150,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-05-31T11:17:00Z', values=$j${"status":"Approved","vendorName":"Apex Materials Pvt Ltd","finalQty":150,"finalRate":1140,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-06-01T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3021","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-04T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5521","materialDispatchDate":"2026-06-09","paymentTerms":"Credit","totalGstValue":201780,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-06', actual_date='2026-06-06T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Credit)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-08T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40147","transportDetails":"Gati Ltd","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1221","receivedQty":150,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=7;

-- PO-2023  (active step 7)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2023', $j${"category":"PACKING MATERIAL","itemName":"Bubble Wrap Rolls","quantity":350,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-30T09:03:00Z', 7, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-05-30T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"Bubble Wrap Rolls","quantity":350,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-05-31T11:17:00Z', values=$j${"status":"Approved","vendorName":"Nexus Polymers","finalQty":350,"finalRate":290,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-06-01T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3022","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-02T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5522","materialDispatchDate":"2026-06-07","paymentTerms":"On Delivery","totalGstValue":119770,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-04', actual_date='2026-06-04T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (On Delivery)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-06', actual_date='2026-06-06T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40154","transportDetails":"TCI Express","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-09', actual_date='2026-06-10T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1222","receivedQty":350,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-11' WHERE entry_id=:'e' AND step_index=7;

-- PO-2024  (active step 8)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2024', $j${"category":"PACKING MATERIAL","itemName":"Stretch Wrap Rolls","quantity":75,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-28T09:03:00Z', 8, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-28', actual_date='2026-05-28T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"Stretch Wrap Rolls","quantity":75,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-29', actual_date='2026-05-29T11:17:00Z', values=$j${"status":"Approved","vendorName":"Global Filtration Co","finalQty":75,"finalRate":1840,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-05-31T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3023","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-06-01T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5523","materialDispatchDate":"2026-06-06","paymentTerms":"Credit","totalGstValue":162840,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-03T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Credit)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-05', actual_date='2026-06-05T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40161","transportDetails":"VRL Logistics","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-09T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1223","receivedQty":75,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/823","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-13' WHERE entry_id=:'e' AND step_index=8;

-- PO-2025  (active step 8)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2025', $j${"category":"PACKING MATERIAL","itemName":"HDPE Drums 50L","quantity":275,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-31T09:03:00Z', 8, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-31', actual_date='2026-05-31T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"HDPE Drums 50L","quantity":275,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-01', actual_date='2026-06-01T11:17:00Z', values=$j${"status":"Approved","vendorName":"Orient Chem Agencies","finalQty":275,"finalRate":1000,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-02T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3024","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-03T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5524","materialDispatchDate":"2026-06-09","paymentTerms":"Advance","totalGstValue":324500,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-05', actual_date='2026-06-05T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Advance)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-08', actual_date='2026-06-07T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40168","transportDetails":"Delhivery Cargo","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-09', actual_date='2026-06-09T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1224","receivedQty":275,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-10', actual_date='2026-06-10T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/824","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-13' WHERE entry_id=:'e' AND step_index=8;

-- PO-2026  (active step 8, overdue)
INSERT INTO public.fms_entries (workflow_id, code, summary, created_by, created_at, current_step_index, status)
VALUES (:'wf', 'PO-2026', $j${"category":"PACKING MATERIAL","itemName":"Carton Sealing Tape","quantity":475,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, :'creator', '2026-05-23T09:03:00Z', 8, 'in_progress')
RETURNING id AS e \gset
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-23', actual_date='2026-05-23T10:10:00Z', values=$j${"category":"PACKING MATERIAL","itemName":"Carton Sealing Tape","quantity":475,"unit":"PCS","remarks":"Standard procurement."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=0;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-25', actual_date='2026-05-24T11:17:00Z', values=$j${"status":"Approved","vendorName":"Sunrise Industrial","finalQty":475,"finalRate":150,"purchaseRemarks":"Approved at agreed rate."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=1;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-25', actual_date='2026-05-25T12:24:00Z', values=$j${"status":"Done","systemPoNo":"PO/2026/3025","poRemarks":"PO generated in ERP and shared."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=2;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-26', actual_date='2026-05-26T13:31:00Z', values=$j${"status":"Done","vendorPiNo":"PI-26-5525","materialDispatchDate":"2026-05-31","paymentTerms":"Partial Advance","totalGstValue":84075,"sharedRemarks":"PI received from vendor."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=3;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-28', actual_date='2026-05-28T14:38:00Z', values=$j${"status":"Done","advRemarks":"Advance released (Partial Advance)."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=4;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-05-30', actual_date='2026-05-31T15:45:00Z', values=$j${"status":"Dispatched","dispatchLr":"LR40175","transportDetails":"Safexpress","followUpRemarks":"Vendor confirmed dispatch."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=5;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-02', actual_date='2026-06-02T10:10:00Z', values=$j${"status":"Received","gateRegisterNo":"GR-1225","receivedQty":475,"receivedCondition":"Good","remarks":"Material received in good condition."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=6;
UPDATE public.fms_entry_stages SET status='done', planned_date='2026-06-03', actual_date='2026-06-05T11:17:00Z', values=$j${"status":"Done","tallyPiNo":"TLY/26/825","systemRemarks":"Purchase booked in Tally."}$j$::jsonb, completed_by=:'creator' WHERE entry_id=:'e' AND step_index=7;
UPDATE public.fms_entry_stages SET status='active', planned_date='2026-06-09' WHERE entry_id=:'e' AND step_index=8;

COMMIT;
