-- GENERATED by db/seed/load_bushra_tasks.py - review before applying.
-- Additive only: recurring tasks for Bushra (idempotent NOT EXISTS guards).
begin;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'EXPENSE', 'ALL EXPENSE REPORT', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'EXPENSE' and t.description = 'ALL EXPENSE REPORT' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'FMS', 'ALL FMS SHEET', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'FMS' and t.description = 'ALL FMS SHEET' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'PRODUCTION', 'BATCH WISE COSTING REPORT (POWERBI)', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'PRODUCTION' and t.description = 'BATCH WISE COSTING REPORT (POWERBI)' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'BRANCH BALANCE SHEET AND P&L MATCHING', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'BRANCH BALANCE SHEET AND P&L MATCHING' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'SALES', 'COLOUR CONSUMPTION WISE SALES REPORT UPDATE', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'SALES' and t.description = 'COLOUR CONSUMPTION WISE SALES REPORT UPDATE' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'SALES', 'CUSTOMER TRACKING SHEET -ACTIVE/INACTIVE', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'SALES' and t.description = 'CUSTOMER TRACKING SHEET -ACTIVE/INACTIVE' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'SALES', 'DAILY SALES REPORT', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'SALES' and t.description = 'DAILY SALES REPORT' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'SALES', 'DAILY SALES REPORT SHARED TO MANAGEMENT', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'SALES' and t.description = 'DAILY SALES REPORT SHARED TO MANAGEMENT' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'AUDIT', 'DEBTOR AGING REPORT', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'AUDIT' and t.description = 'DEBTOR AGING REPORT' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'GP REPORT -HEAD', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'GP REPORT -HEAD' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'GP REPORT -INK', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'GP REPORT -INK' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'GP REPORT -PAPER', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'GP REPORT -PAPER' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'GP REPORT -SPARE PARTS', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'GP REPORT -SPARE PARTS' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'IMPORT DATA DASHBOARD', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'IMPORT DATA DASHBOARD' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'IMS', 'IMS SHEET -HEAD', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'IMS' and t.description = 'IMS SHEET -HEAD' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'IMS', 'IMS SHEET -INK', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'IMS' and t.description = 'IMS SHEET -INK' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'IMS', 'IMS SHEET -MACHINE', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'IMS' and t.description = 'IMS SHEET -MACHINE' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'IMS', 'IMS SHEET -PACKING MATERIAL', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'IMS' and t.description = 'IMS SHEET -PACKING MATERIAL' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'IMS', 'IMS SHEET -RAW MATERIAL', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'IMS' and t.description = 'IMS SHEET -RAW MATERIAL' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'IMS', 'IMS SHEET -SPARE PARTS', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'IMS' and t.description = 'IMS SHEET -SPARE PARTS' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'P&L & BS REPORT', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'P&L & BS REPORT' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'PURCHASE', 'PRODUCT WISE PURCHASE REPORT UPDATE', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'PURCHASE' and t.description = 'PRODUCT WISE PURCHASE REPORT UPDATE' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'SALES', 'PRODUCT WISE SALES REPORT UPDATE', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'SALES' and t.description = 'PRODUCT WISE SALES REPORT UPDATE' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'PURCHASE', 'PURCHASE REPORT', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'PURCHASE' and t.description = 'PURCHASE REPORT' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'RELATED PARTY BALANCE SHEET AND P&L MATCHING', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'RELATED PARTY BALANCE SHEET AND P&L MATCHING' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'AUDIT', 'STOCK VALUATION', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'AUDIT' and t.description = 'STOCK VALUATION' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'REPORTING', 'TARGET VS ACHIEVEMENT DASHBOARD UPDATE AND SHARED WITH SALES REPORT', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'REPORTING' and t.description = 'TARGET VS ACHIEVEMENT DASHBOARD UPDATE AND SHARED WITH SALES REPORT' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'AUDIT', 'INVENTORY AGING REPORT', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'AUDIT' and t.description = 'INVENTORY AGING REPORT' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'AUDIT', 'CUSTOMER AGING REPORT', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'AUDIT' and t.description = 'CUSTOMER AGING REPORT' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'AUDIT', 'VENDOR AGING REPORT', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'AUDIT' and t.description = 'VENDOR AGING REPORT' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

commit;

-- After applying, materialise today's instances:
--   select public.generate_recurring_tasks();
