-- GENERATED by db/seed/load_jayshree_tasks.py - review before applying.
-- Additive only: recurring tasks for Jayshree Patil (idempotent NOT EXISTS guards).
begin;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Collection', 'Take entry in Tally before depositing cheques in the bank.', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Collection' and t.description = 'Take entry in Tally before depositing cheques in the bank.' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Collection', 'Confirm whether ink and part is given to customers based on payment status, and inform customers whose ink or part are on hold.', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Collection' and t.description = 'Confirm whether ink and part is given to customers based on payment status, and inform customers whose ink or part are on hold.' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Collection', 'Update collection sheet.', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Collection' and t.description = 'Update collection sheet.' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Collection', 'Customer payment follow-up.', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Collection' and t.description = 'Customer payment follow-up.' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Meeting', 'Meet salesperson and discuss about payment.', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Meeting' and t.description = 'Meet salesperson and discuss about payment.' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Update machine PDC sheet weekly.', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Reporting' and t.description = 'Update machine PDC sheet weekly.' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Update dispute sheet weekly.', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Reporting' and t.description = 'Update dispute sheet weekly.' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Share due sheet to salesperson.', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Reporting' and t.description = 'Share due sheet to salesperson.' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Make redmark customer list.', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Reporting' and t.description = 'Make redmark customer list.' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Homer machine licence confirmation.', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Reporting' and t.description = 'Homer machine licence confirmation.' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Make overdue report.', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Reporting' and t.description = 'Make overdue report.' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Make dispute report.', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Reporting' and t.description = 'Make dispute report.' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Make PDC report.', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Reporting' and t.description = 'Make PDC report.' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Meeting', 'Check ledgers and resolve disputes related to them.', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Meeting' and t.description = 'Check ledgers and resolve disputes related to them.' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Meeting', 'Resolve customer queries regarding: ink rate, FOC parts or FOC ink, ink return matters. Coordinate with Director and Salesperson for resolution.', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Meeting' and t.description = 'Resolve customer queries regarding: ink rate, FOC parts or FOC ink, ink return matters. Coordinate with Director and Salesperson for resolution.' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Meeting', 'If there are any legal matters then send all documents related to it to advocate.', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'bb096b8e-bbae-4476-ae6b-89111fbad4bd', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bb096b8e-bbae-4476-ae6b-89111fbad4bd'
      and t.title = 'Meeting' and t.description = 'If there are any legal matters then send all documents related to it to advocate.' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

commit;

-- After applying, materialise today's instances:
--   select public.generate_recurring_tasks();
