#!/usr/bin/env python3
"""
Order to Dispatch: the customer LOCATION, loaded from the "Customer-location
mapping" workbook (Misc/Bushra Reports) -> fms_dispatch_customers.location.

EMITS reviewable SQL. Nothing is written to the database by this script; apply the
generated SQL yourself after review:

    python db/seed/load_fms_dispatch_customer_locations.py
    psql "$SUPABASE_DB_URL" -f db/seed/fms_dispatch_customer_locations_load.sql
    # or paste that file into the Supabase SQL editor

WHAT IT TOUCHES, and what it deliberately does not:
  - it UPDATES the location of customers that already exist, matched on the name;
  - it never INSERTS a customer. A party in the sheet that is not in the master is
    reported, not created: the sheet is a location list, not a customer master, and
    a name typed slightly differently would otherwise become a second customer that
    no order can ever use.

LOCATIONS ARE UPPERCASED. The intake form offers every location anyone has used, so
"Sachin", "SACHIN" and "sachin" would sit in that list as three different places.
One casing, decided here and enforced on save in the app (lib/masterFields.ts).
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / "Misc" / "Bushra Reports" / "Customer-location mapping.xlsx"
OUT = ROOT / "db" / "seed" / "fms_dispatch_customer_locations_load.sql"

# Pivot-table leftovers in the source sheet — a row, but not a party.
NOT_A_PARTY = {"GRAND TOTAL", "TOTAL", "PARTY NAME - 2"}


def q(v: str) -> str:
    """A single-quoted SQL literal."""
    return "'" + v.replace("'", "''") + "'"


def clean(v: object) -> str:
    """
    A cell, as text.

    ⚠ `_x000D_` IS NOT PART OF ANYBODY'S NAME. Excel stores a line break inside a
      cell as that escape, and openpyxl hands it back verbatim — one party in this
      sheet carries it, and it matched no customer until it was stripped. Real
      control characters get the same treatment, and internal runs of whitespace
      collapse, because "PVT  LTD" and "PVT LTD" are the same company.
    """
    text = re.sub(r"_x000[dDaA]_", " ", str(v or ""))
    return re.sub(r"\s+", " ", text.replace("\r", " ").replace("\n", " ")).strip()


def read_pairs(path: Path) -> list[tuple[str, str]]:
    ws = load_workbook(path, read_only=True, data_only=True).worksheets[0]
    pairs: dict[str, str] = {}
    for name_cell, loc_cell in ws.iter_rows(min_row=2, max_col=2, values_only=True):
        name = clean(name_cell)
        location = clean(loc_cell).upper()
        if not name or not location or name.upper() in NOT_A_PARTY:
            continue
        # Last one wins, and a repeat is only a repeat when it agrees with itself —
        # a party listed twice under two locations is a question for the sheet, so
        # say so rather than silently picking one.
        prior = pairs.get(name.upper())
        if prior and prior != location:
            raise SystemExit(f"{name!r} is listed under both {prior!r} and {location!r} — fix the sheet.")
        pairs[name.upper()] = location
    return sorted(pairs.items())


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--file", type=Path, default=DEFAULT_SOURCE, help="source .xlsx")
    args = ap.parse_args()

    pairs = read_pairs(args.file)
    values = ",\n  ".join(f"({q(name)}, {q(loc)})" for name, loc in pairs)
    locations = sorted({loc for _, loc in pairs})

    sql = f"""-- Order to Dispatch — CUSTOMER LOCATIONS, from "{args.file.name}".
-- GENERATED by db/seed/load_fms_dispatch_customer_locations.py — do not hand-edit;
-- fix the sheet and re-run the loader.
--
--   psql "$SUPABASE_DB_URL" -f db/seed/fms_dispatch_customer_locations_load.sql
--
-- {len(pairs)} parties across {len(locations)} locations, ALL UPPERCASED — the intake
-- form offers every location anyone has used, and mixed casing would put the same
-- place in that list two and three times over.
--
-- ⚠ UPDATE-ONLY, and matched on the NAME. A party in the sheet with no customer of
--   that name is REPORTED at the end, never inserted: this sheet says where a
--   customer is, not that they exist. Re-running is safe and changes nothing twice.

begin;

create temporary table tmp_dispatch_customer_location (
  party_name text primary key,
  location   text not null
) on commit drop;

insert into tmp_dispatch_customer_location (party_name, location) values
  {values};

-- 1. The mapping itself. Names are compared upper+trimmed, because the sheet and the
--    master disagree about spacing and capitals far more often than about spelling.
update public.fms_dispatch_customers c
   set location = t.location,
       updated_at = now()
  from tmp_dispatch_customer_location t
 where upper(trim(c.name)) = t.party_name
   and coalesce(c.location, '') is distinct from t.location;

-- 2. Every OTHER customer's location goes caps too — the ones typed in by hand
--    before this rule existed. Same place, one spelling.
update public.fms_dispatch_customers
   set location = upper(trim(location)),
       updated_at = now()
 where location is not null
   and location <> upper(trim(location));

-- 3. And the locations already typed onto ORDERS, which is the other half of the
--    intake picker's list. This changes the CASE of a delivery point, never the
--    place — an order still says where it went.
update public.fms_dispatch_orders
   set customer_location = upper(trim(customer_location))
 where customer_location is not null
   and customer_location <> upper(trim(customer_location));

-- ---------------------------------------------------------------- report --
do $report$
declare
  v_missing text;
  v_blank   int;
begin
  select string_agg(t.party_name, ', ' order by t.party_name)
    into v_missing
    from tmp_dispatch_customer_location t
   where not exists (
     select 1 from public.fms_dispatch_customers c where upper(trim(c.name)) = t.party_name
   );

  select count(*) into v_blank
    from public.fms_dispatch_customers
   where active and coalesce(trim(location), '') = '';

  if v_missing is not null then
    raise notice 'NOT IN THE CUSTOMER MASTER (no customer of this name, nothing written): %', v_missing;
  end if;
  raise notice 'Active customers still without a location: %', v_blank;
end $report$;

commit;
"""
    OUT.write_text(sql, encoding="utf-8")
    print(f"{len(pairs)} parties, {len(locations)} locations -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
