-- GENERATED by db/seed/load_ritesh_tasks.py — review before applying.
-- Additive only: recurring tasks for Ritesh (+ Dimple/Bushra for dated rows).
-- Idempotent NOT-EXISTS guards. Requires migration 0020 (prepone_off_holidays).
begin;

-- row 2: Inventory / Review -Head Entry
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Head Entry', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Head Entry' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 3: Inventory / Review -Head entry Match with Gorakh
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Head entry Match with Gorakh', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Head entry Match with Gorakh' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 4: Inventory / Review -Head entry Match with Auditor
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Head entry Match with Auditor', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Head entry Match with Auditor' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 5: Machine / Review -Machine Sales GP report
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Machine', 'Review -Machine Sales GP report', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Machine' and t.description = 'Review -Machine Sales GP report' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 6: Machine / Review -Monthly Machine Sales GP report
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Machine', 'Review -Monthly Machine Sales GP report', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Machine' and t.description = 'Review -Monthly Machine Sales GP report' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 7: Fund Flow / Review -Updation of Fund Flow
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Fund Flow', 'Review -Updation of Fund Flow', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Fund Flow' and t.description = 'Review -Updation of Fund Flow' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 8: Fund Flow / Review -Matching of Fund Flow with Bank Balance
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Fund Flow', 'Review -Matching of Fund Flow with Bank Balance', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Fund Flow' and t.description = 'Review -Matching of Fund Flow with Bank Balance' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 9: Fund Flow / Review -Projected Fund Flow
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Fund Flow', 'Review -Projected Fund Flow', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Fund Flow' and t.description = 'Review -Projected Fund Flow' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 10: Inventory / Review -Import Compensation from Suppliers
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Import Compensation from Suppliers', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Import Compensation from Suppliers' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 11: Inventory / Review -Entry of Compensation in Tally
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Entry of Compensation in Tally', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Entry of Compensation in Tally' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 12: Stock Statements / Review -Submission of Stock Statement
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Stock Statements', 'Review -Submission of Stock Statement', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Stock Statements' and t.description = 'Review -Submission of Stock Statement' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 13: Compliance / Review -TDS Payment
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Compliance', 'Review -TDS Payment', 'monthly', '{}'::int[], '{7}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Compliance' and t.description = 'Review -TDS Payment' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Compliance', 'Review -TDS Payment', 'monthly', '{}'::int[], '{7}'::int[], NULL, NULL,
         'e27f15d6-6335-4387-8842-fd883988dab4', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'e27f15d6-6335-4387-8842-fd883988dab4'
      and t.title = 'Compliance' and t.description = 'Review -TDS Payment' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 14: Compliance / Review -GST Payment
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Compliance', 'Review -GST Payment', 'monthly', '{}'::int[], '{21}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Compliance' and t.description = 'Review -GST Payment' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Compliance', 'Review -GST Payment', 'monthly', '{}'::int[], '{21}'::int[], NULL, NULL,
         'e27f15d6-6335-4387-8842-fd883988dab4', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'e27f15d6-6335-4387-8842-fd883988dab4'
      and t.title = 'Compliance' and t.description = 'Review -GST Payment' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 15: Compliance / Review -PF and ESIC Payment
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Compliance', 'Review -PF and ESIC Payment', 'monthly', '{}'::int[], '{15}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Compliance' and t.description = 'Review -PF and ESIC Payment' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Compliance', 'Review -PF and ESIC Payment', 'monthly', '{}'::int[], '{15}'::int[], NULL, NULL,
         'e27f15d6-6335-4387-8842-fd883988dab4', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'e27f15d6-6335-4387-8842-fd883988dab4'
      and t.title = 'Compliance' and t.description = 'Review -PF and ESIC Payment' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 16: Inventory / Review -Stock Adjustment entry tally
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Stock Adjustment entry tally', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Stock Adjustment entry tally' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 17: Expenses / Review -Commission Working
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Expenses', 'Review -Commission Working', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Expenses' and t.description = 'Review -Commission Working' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 18: Expenses / Review -Salary Entry
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Expenses', 'Review -Salary Entry', 'monthly', '{}'::int[], '{5}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Expenses' and t.description = 'Review -Salary Entry' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Expenses', 'Review -Salary Entry', 'monthly', '{}'::int[], '{6}'::int[], NULL, NULL,
         'e27f15d6-6335-4387-8842-fd883988dab4', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'e27f15d6-6335-4387-8842-fd883988dab4'
      and t.title = 'Expenses' and t.description = 'Review -Salary Entry' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 19: Expenses / Review -Director Salary Payment
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Expenses', 'Review -Director Salary Payment', 'monthly', '{}'::int[], '{6}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Expenses' and t.description = 'Review -Director Salary Payment' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Expenses', 'Review -Director Salary Payment', 'monthly', '{}'::int[], '{6}'::int[], NULL, NULL,
         'e27f15d6-6335-4387-8842-fd883988dab4', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'e27f15d6-6335-4387-8842-fd883988dab4'
      and t.title = 'Expenses' and t.description = 'Review -Director Salary Payment' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 20: Fund Flow / Review -Hanglory Dues Statement
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Fund Flow', 'Review -Hanglory Dues Statement', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Fund Flow' and t.description = 'Review -Hanglory Dues Statement' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 21: Inventory / Review -Machine order sheet
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Machine order sheet', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Machine order sheet' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 22: MIS / Review -List of Advance received from Debtors
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'MIS', 'Review -List of Advance received from Debtors', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'MIS' and t.description = 'Review -List of Advance received from Debtors' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 23: MIS / Review -List of Advance paid to Creditors with Reason
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'MIS', 'Review -List of Advance paid to Creditors with Reason', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'MIS' and t.description = 'Review -List of Advance paid to Creditors with Reason' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 24: Inventory / Review -Total FOC Payable
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Total FOC Payable', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Total FOC Payable' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 25: Inventory / Review -Total FOC Receivable
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Total FOC Receivable', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Total FOC Receivable' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 26: Debtors / Review -Exchange on Machines Sales(Customer)
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Debtors', 'Review -Exchange on Machines Sales(Customer)', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Debtors' and t.description = 'Review -Exchange on Machines Sales(Customer)' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 27: Inventory / Review -FOC Spare payable report
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -FOC Spare payable report', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -FOC Spare payable report' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 28: Bank / Review -Verify the Bank Payment to vendor
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Bank', 'Review -Verify the Bank Payment to vendor', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Bank' and t.description = 'Review -Verify the Bank Payment to vendor' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 29: Bank / Review -Approve the Bank Payment to vendor
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Bank', 'Review -Approve the Bank Payment to vendor', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Bank' and t.description = 'Review -Approve the Bank Payment to vendor' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 30: Bank / Review -Sharing of Bank Statement to team twice
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Bank', 'Review -Sharing of Bank Statement to team twice', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Bank' and t.description = 'Review -Sharing of Bank Statement to team twice' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 31: Inventory / Review -Physical stock - Data to be shared to team
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Physical stock - Data to be shared to team', 'monthly', '{}'::int[], '{1,15}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Physical stock - Data to be shared to team' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 32: Inventory / Review -Physical stock - Data to be shared to team
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Inventory', 'Review -Physical stock - Data to be shared to team', 'monthly', '{}'::int[], '{1,15}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Inventory' and t.description = 'Review -Physical stock - Data to be shared to team' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 33: Audit coordination / Review -Audit closer
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Audit coordination', 'Review -Audit closer', 'quarterly', '{}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Audit coordination' and t.description = 'Review -Audit closer' and t.recurrence_type = 'quarterly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 34: Debtors reco. / Review -Solve Debtors Reco. mismatch with their accountant and do necessery action like need to issue credit note
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'Debtors reco.', 'Review -Solve Debtors Reco. mismatch with their accountant and do necessery action like need to issue credit note', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, false
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'Debtors reco.' and t.description = 'Review -Solve Debtors Reco. mismatch with their accountant and do necessery action like need to issue credit note' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 35: MIS / Review of Balance Sheet
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'MIS', 'Review of Balance Sheet', 'monthly', '{}'::int[], '{8}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'MIS' and t.description = 'Review of Balance Sheet' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'MIS', 'Review of Balance Sheet', 'monthly', '{}'::int[], '{9}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'MIS' and t.description = 'Review of Balance Sheet' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 36: MIS / Review of P&L
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'MIS', 'Review of P&L', 'monthly', '{}'::int[], '{8}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'MIS' and t.description = 'Review of P&L' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'MIS', 'Review of P&L', 'monthly', '{}'::int[], '{9}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'MIS' and t.description = 'Review of P&L' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

-- row 37: MIS / Review of Expenses
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'MIS', 'Review of Expenses', 'monthly', '{}'::int[], '{8}'::int[], NULL, NULL,
         'a43038e5-1c05-45b0-b316-9e87bbb2b11b', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'a43038e5-1c05-45b0-b316-9e87bbb2b11b'
      and t.title = 'MIS' and t.description = 'Review of Expenses' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active, prepone_off_holidays)
  select 'MIS', 'Review of Expenses', 'monthly', '{}'::int[], '{9}'::int[], NULL, NULL,
         '79174071-1f03-46dd-bdf7-a6a7d3699877', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true, true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '79174071-1f03-46dd-bdf7-a6a7d3699877'
      and t.title = 'MIS' and t.description = 'Review of Expenses' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select id, 'e98c2cf0-ca28-446e-8633-f99291f3d058'::uuid from ins
  union all
  select id, '940fa09a-6472-4249-b17e-d47818159a06'::uuid from ins
  union all
  select id, 'd7c30d44-997f-4eb4-bce6-35339ad0f86d'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

commit;

-- After applying, materialise today's instances:
--   select public.generate_recurring_tasks();
