-- GENERATED by db/seed/load_task_list.py — review before applying.
-- Additive only: creates 3 locations + recurring tasks (idempotent guards).
begin;

-- 1. new standalone locations (company NULL -> label is just the name)
insert into public.locations (company, name, is_general, active, sort_order, created_by)
select null, 'Ink Jet', false, true, 5, '79174071-1f03-46dd-bdf7-a6a7d3699877'
where not exists (select 1 from public.locations where name = 'Ink Jet' and company is null);
insert into public.locations (company, name, is_general, active, sort_order, created_by)
select null, 'Colorix', false, true, 6, '79174071-1f03-46dd-bdf7-a6a7d3699877'
where not exists (select 1 from public.locations where name = 'Colorix' and company is null);
insert into public.locations (company, name, is_general, active, sort_order, created_by)
select null, 'Personal Accounts', false, true, 7, '79174071-1f03-46dd-bdf7-a6a7d3699877'
where not exists (select 1 from public.locations where name = 'Personal Accounts' and company is null);

-- 2. recurring tasks (title=Category, description=Task) + location checklist
with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Sales', 'Daily Posting of Sales Invoices -INK', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Sales' and t.description = 'Daily Posting of Sales Invoices -INK' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Sales', 'Daily Posting of Sales Invoices -Spare Parts', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Sales' and t.description = 'Daily Posting of Sales Invoices -Spare Parts' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Sales', 'Daily Posting of Sales Invoices -Heads', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Sales' and t.description = 'Daily Posting of Sales Invoices -Heads' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Sales', 'Daily Posting of Sales Invoices -Machines', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Sales' and t.description = 'Daily Posting of Sales Invoices -Machines' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Sales', 'Daily Posting of Sales Invoices -Paper', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Sales' and t.description = 'Daily Posting of Sales Invoices -Paper' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Sales', 'Daily Posting of Sales Invoices -Service', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Sales' and t.description = 'Daily Posting of Sales Invoices -Service' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Sales', 'Updating of the credit limit EMAIL TO MGT', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Sales' and t.description = 'Updating of the credit limit EMAIL TO MGT' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'OC PI', 'Preparing on Signed OC and PI', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'OC PI' and t.description = 'Preparing on Signed OC and PI' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'OC PI', 'Sharing the same with Sales Team', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'OC PI' and t.description = 'Sharing the same with Sales Team' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'OC PI', 'Follow up with Customer for the signed OC and PI', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'OC PI' and t.description = 'Follow up with Customer for the signed OC and PI' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'PO', 'Posting of Purchase Order and signing  -  INK Local', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'PO' and t.description = 'Posting of Purchase Order and signing  -  INK Local' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'PO', 'Posting of Purchase Order and signing - Dryer Local', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'PO' and t.description = 'Posting of Purchase Order and signing - Dryer Local' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'PO', 'Posting of Purchase Order and signing - HEADS', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'PO' and t.description = 'Posting of Purchase Order and signing - HEADS' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'PO', 'Posting of Purchase Order and signing - SPARE PARTS', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'PO' and t.description = 'Posting of Purchase Order and signing - SPARE PARTS' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'PO', 'Posting of Purchase Order and signing - OTHERS', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'PO' and t.description = 'Posting of Purchase Order and signing - OTHERS' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Rejection', 'Daily Rejection Entries of head and spare parts', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Rejection' and t.description = 'Daily Rejection Entries of head and spare parts' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Sales Invoice Receiving confirmation from Hojiwala and Sachin (Status Report)', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Reporting' and t.description = 'Sales Invoice Receiving confirmation from Hojiwala and Sachin (Status Report)' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Signed OC and PI from Customer (Status)', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Reporting' and t.description = 'Signed OC and PI from Customer (Status)' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Air Cargo receipt status - Harshit -sparepart', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Reporting' and t.description = 'Air Cargo receipt status - Harshit -sparepart' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Air Cargo receipt status - Murli - Head', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Reporting' and t.description = 'Air Cargo receipt status - Murli - Head' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Tally', 'Customer wise price list- ink', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Tally' and t.description = 'Customer wise price list- ink' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Tally', 'Customer wise price list- spare parts', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Tally' and t.description = 'Customer wise price list- spare parts' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Tally', 'Updating of the credit limit of customer', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Tally' and t.description = 'Updating of the credit limit of customer' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Tally', 'Customer wise price list- ink', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Tally' and t.description = 'Customer wise price list- ink' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Tally', 'Customer wise price list- spare parts', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Tally' and t.description = 'Customer wise price list- spare parts' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Tally', 'Updating of the credit limit of customer', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Tally' and t.description = 'Updating of the credit limit of customer' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Status of confirmation of invoice Hojiwala and Sachine', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Reporting' and t.description = 'Status of confirmation of invoice Hojiwala and Sachine' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'SOA pending with reason for machine', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Reporting' and t.description = 'SOA pending with reason for machine' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'SOA pending with reason for other then machine', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Reporting' and t.description = 'SOA pending with reason for other then machine' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Audit', 'Quarterly email Customer ledger confirmation', 'quarterly', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Audit' and t.description = 'Quarterly email Customer ledger confirmation' and t.recurrence_type = 'quarterly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Audit', 'Filling', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '261ae1c1-9389-427a-9fa3-1c8df7326f73', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '261ae1c1-9389-427a-9fa3-1c8df7326f73'
      and t.title = 'Audit' and t.description = 'Filling' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Expenses', 'Expense Entry', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'fde9faec-c6f5-4670-91b6-5e4ee4c085ff', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'fde9faec-c6f5-4670-91b6-5e4ee4c085ff'
      and t.title = 'Expenses' and t.description = 'Expense Entry' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Bank', 'Bank Payment Entry - For Making Payment online', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'fde9faec-c6f5-4670-91b6-5e4ee4c085ff', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'fde9faec-c6f5-4670-91b6-5e4ee4c085ff'
      and t.title = 'Bank' and t.description = 'Bank Payment Entry - For Making Payment online' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Bank', 'Bank Payment file and Upload in Axis and Excel file', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'fde9faec-c6f5-4670-91b6-5e4ee4c085ff', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'fde9faec-c6f5-4670-91b6-5e4ee4c085ff'
      and t.title = 'Bank' and t.description = 'Bank Payment file and Upload in Axis and Excel file' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Bank', 'Sharing of URT Details', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'fde9faec-c6f5-4670-91b6-5e4ee4c085ff', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'fde9faec-c6f5-4670-91b6-5e4ee4c085ff'
      and t.title = 'Bank' and t.description = 'Sharing of URT Details' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Bank', 'All Bank Related Work and Follow up', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'fde9faec-c6f5-4670-91b6-5e4ee4c085ff', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'fde9faec-c6f5-4670-91b6-5e4ee4c085ff'
      and t.title = 'Bank' and t.description = 'All Bank Related Work and Follow up' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Expenses', 'Update Expenses', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'fde9faec-c6f5-4670-91b6-5e4ee4c085ff', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'fde9faec-c6f5-4670-91b6-5e4ee4c085ff'
      and t.title = 'Expenses' and t.description = 'Update Expenses' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Expenses', 'Follow up with Creditors with Debit Balance', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'fde9faec-c6f5-4670-91b6-5e4ee4c085ff', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'fde9faec-c6f5-4670-91b6-5e4ee4c085ff'
      and t.title = 'Expenses' and t.description = 'Follow up with Creditors with Debit Balance' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Cash', 'Cash Payment entry', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Cash' and t.description = 'Cash Payment entry' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Audit', 'Filling', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         'fde9faec-c6f5-4670-91b6-5e4ee4c085ff', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'fde9faec-c6f5-4670-91b6-5e4ee4c085ff'
      and t.title = 'Audit' and t.description = 'Filling' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Expenses', 'Expense Entry', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Expenses' and t.description = 'Expense Entry' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Bank', 'PDC Cheque entry', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Bank' and t.description = 'PDC Cheque entry' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Expenses', 'Credit Card Entry', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Expenses' and t.description = 'Credit Card Entry' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Expenses', 'Job Card Entry', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Expenses' and t.description = 'Job Card Entry' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Bank', 'BRS', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Bank' and t.description = 'BRS' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Expenses', 'MSME Follow Up', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Expenses' and t.description = 'MSME Follow Up' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Expenses', 'TDS Refund Follow up', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Expenses' and t.description = 'TDS Refund Follow up' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Bank', 'Bank Receipt and payment entry', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Bank' and t.description = 'Bank Receipt and payment entry' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Personal A/c', 'Directors Personal A/c Entry', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Personal A/c' and t.description = 'Directors Personal A/c Entry' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select ins.id, l.id from ins, public.locations l where l.name = 'Personal Accounts' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Audit', 'Filling', 'daily', '{}'::int[], '{}'::int[], NULL, NULL,
         '0600d53e-8077-4ee6-9f12-239d3c198558', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '0600d53e-8077-4ee6-9f12-239d3c198558'
      and t.title = 'Audit' and t.description = 'Filling' and t.recurrence_type = 'daily')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Purchase', 'Domestic Good Purchase', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Purchase' and t.description = 'Domestic Good Purchase' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Purchase', 'Import Good Purchase', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Purchase' and t.description = 'Import Good Purchase' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Purchase', 'Credit Notes/ Sales Return/ Purchase Returns', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Purchase' and t.description = 'Credit Notes/ Sales Return/ Purchase Returns' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Inventory', 'Stock entry form Machines', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Inventory' and t.description = 'Stock entry form Machines' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Inventory', 'Head Entry', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Inventory' and t.description = 'Head Entry' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Purchase', 'Duty Bifurcation entry', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Purchase' and t.description = 'Duty Bifurcation entry' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'Lanyu Due Sheet', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Reporting' and t.description = 'Lanyu Due Sheet' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'GP Reprots-INK', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Reporting' and t.description = 'GP Reprots-INK' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'GP Reprots-HEADS', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Reporting' and t.description = 'GP Reprots-HEADS' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'GP Reprots-SPARE PARTS', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Reporting' and t.description = 'GP Reprots-SPARE PARTS' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Reporting', 'GP Reprots-Paper', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         'bf164ac0-e945-427b-9a99-89a3f5018956', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = 'bf164ac0-e945-427b-9a99-89a3f5018956'
      and t.title = 'Reporting' and t.description = 'GP Reprots-Paper' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Forex', 'Forex Entry and preparing of reprots', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Forex' and t.description = 'Forex Entry and preparing of reprots' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Forex', 'Import Due Sheet', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Forex' and t.description = 'Import Due Sheet' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Compliance', 'TDS', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Compliance' and t.description = 'TDS' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Compliance', 'GST & ISD', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Compliance' and t.description = 'GST & ISD' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Inventory', 'Stock entry form Machines', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Inventory' and t.description = 'Stock entry form Machines' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Inventory', 'Head Entry', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Inventory' and t.description = 'Head Entry' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Forex', 'USD Dollar working for Customer', 'monthly', '{}'::int[], '{}'::int[], 1, 6,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Forex' and t.description = 'USD Dollar working for Customer' and t.recurrence_type = 'monthly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Commission', 'Commission working', 'when', '{}'::int[], '{}'::int[], NULL, NULL,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Commission' and t.description = 'Commission working' and t.recurrence_type = 'when')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

with ins as (
  insert into public.recurring_tasks
    (title, description, recurrence_type, weekly_days, monthly_days, monthly_nth, monthly_weekday,
     assigned_to, created_by, department_id, active)
  select 'Inventory', 'Physical Stock Comparison', 'weekly', '{1}'::int[], '{}'::int[], NULL, NULL,
         '42653aeb-7c22-4be9-91a8-44513e2d291d', '79174071-1f03-46dd-bdf7-a6a7d3699877', 'f64dfa08-103d-45bd-ba29-1079d774b526', true
  where not exists (
    select 1 from public.recurring_tasks t
    where t.created_by = '79174071-1f03-46dd-bdf7-a6a7d3699877' and t.assigned_to = '42653aeb-7c22-4be9-91a8-44513e2d291d'
      and t.title = 'Inventory' and t.description = 'Physical Stock Comparison' and t.recurrence_type = 'weekly')
  returning id
)
insert into public.recurring_task_locations (recurring_task_id, location_id)
  select id, '01c1f41e-50fa-459f-b21b-f098fdf204b0'::uuid from ins
  union all
  select id, '1c9c6c9f-6fa2-450b-b883-64fbfe9cd882'::uuid from ins
  union all
  select id, '2943b5b6-a1d9-4afc-a38b-381425d1dd6c'::uuid from ins
  union all
  select id, '521b79c0-80df-480d-a130-7d946b7683ae'::uuid from ins
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Ink Jet' and l.company is null
  union all
  select ins.id, l.id from ins, public.locations l where l.name = 'Colorix' and l.company is null
on conflict (recurring_task_id, location_id) do nothing;

commit;

-- After applying, materialise today's instances:
--   select public.generate_recurring_tasks();
