/**
 * Tanisha's sheet, transcribed (KPI-3, read-only).
 *
 * SOURCE: files/Tanisha_Tikde_Final_Revised_KRA_KPI_Travel_Desk_2026.docx — "ORANGE O TEC ·
 * FINAL REVISED KRA & KPI FRAMEWORK · Travel Desk Focus | Orange Hub Mapping Ready".
 *
 * Every `targetText` and `evidence` below is the document's own wording, copied, not
 * paraphrased. `coverage` and `gap` are NOT from the document: they are what the hub can
 * actually honour, read off the live schema and a full walk of the Travel Desk module on
 * 24-09-2026 (one trip from request to settlement, as an admin and again as the traveller
 * and as the desk).
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * ⚠ THE DOCUMENT CONTRADICTS ITSELF ON TWO WEIGHTS, AND THIS FILE TAKES THE DETAIL.
 *
 *   Section 1's summary table          The detailed section that follows
 *   1 Travel, Ticketing …  30%         §2 "KRA Weightage: 25%"
 *   4 Orange Hub FMS  …    15%         §5 "KRA Weightage: 20%"
 *
 * Both columns total 100%, so neither is obviously the typo. The DETAIL is taken because
 * it is corroborated twice over: each detailed section states its own weight AND its
 * per-KPI weights add up to exactly that weight (25 and 20), whereas the summary table's
 * two figures are asserted once and nowhere else. Five percent of somebody's appraisal
 * hangs on it — HR has to say which is right, and until they do this file's split is a
 * reading, not the answer.
 *
 * ⚠ TANISHA'S REPORTING MANAGER IS NAMED "Riya Chauhan, HR Head" ON THE DOCUMENT. The HR
 *   Head in the hub is Riya KUMARI, and there is no Riya Chauhan on the directory. Almost
 *   certainly the same person under a wrong surname, but it is a name on a signed
 *   appraisal, so it is flagged rather than corrected.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * ── Why so much of this sheet reads "Built · not live" ───────────────────────
 * Travel Desk is complete — ten phases, every screen, the money engine in SQL — and has
 * been deliberately ON HOLD since 03-09-2026. Until 24-09-2026 it had ZERO app_access
 * grants and ZERO step owners, so nobody but an admin could open it and no step had an
 * owner. That is a go-live, not a build: the lines below marked `not-released` need
 * somebody to say "start using it", not a developer.
 *
 * ⚠ AND ONE THING THAT IS A BUILD: `travel-desk` IS NOT IN THE NIGHTLY kpi_facts RUN.
 *   The run covers hr, ocpi, import, purchase, sampling, office-supplies, task-management,
 *   production-entry and order-to-dispatch. So KRA 4 — the biggest single line on this
 *   sheet at 10% — scores Tanisha on her Task Management work and is BLIND to every trip
 *   she books. Her own module does not reach her own scorecard.
 */
import type { Framework, KpiLine } from "./types";

/** Task Management's module key in kpi_facts. `travel-desk` has no key — see the header. */
const TASKS = "task-management";

const lines: KpiLine[] = [
  // ══ KRA 1 · Travel, Ticketing & Hotel Booking — 25% ═════════════════════════
  {
    code: "1.1",
    kra: "1",
    group: "",
    title: "Travel request acknowledgement",
    weight: 3,
    measure: "sla",
    targetText: "Within 30 minutes during working hours",
    target: 100,
    unit: "%",
    evidence: "Request receipt and acknowledgement timestamp",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "Two problems, both structural. A trip carries no acknowledgement event at all — the desk's first recorded act is the booking. And every SLA in the module is in WORKING DAYS; a 30-minute clock cannot be expressed by the step engine, which is shared with nine other modules.",
  },
  {
    code: "1.2",
    kra: "1",
    group: "",
    title: "Ticket and booking option comparison",
    weight: 5,
    measure: "ratio",
    targetText: "Minimum 2 viable options for planned travel; best available option for emergency travel",
    target: 100,
    unit: "%",
    evidence: "Comparison covering fare, timing, baggage, cancellation and convenience",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "Nothing records the options that were NOT taken. The booking screen captures what was booked — carrier, PNR, fare, taxes — and has no place to put the two quotes it was chosen against. This is the single biggest hole between the sheet and the module.",
  },
  {
    code: "1.3",
    kra: "1",
    group: "",
    title: "Domestic booking confirmation",
    weight: 4,
    measure: "sla",
    targetText: "Same working day after approval",
    target: 100,
    unit: "%",
    evidence: "Approved request, PNR/ticket and confirmation timestamp",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "Fully measurable: the Booking step is stamped and anchored on the last approval, and Desk Performance already reports its median. Two catches — the step's configured SLA is 2 working days, not the same day this sheet asks for, and travel-desk produces no kpi_facts rows so nothing feeds a score.",
  },
  {
    code: "1.4",
    kra: "1",
    group: "",
    title: "International travel coordination",
    weight: 4,
    measure: "ratio",
    targetText: "100% checklist compliance before booking",
    target: 100,
    unit: "%",
    evidence: "Passport validity, visa/approval checklist, itinerary and booking proof",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "The module implements the DOMESTIC Travel Policy and nothing else. No passport field, no visa checklist, no foreign currency, no international entitlement on any rate card. A build, and not a small one.",
  },
  {
    code: "1.5",
    kra: "1",
    group: "",
    title: "Hotel and accommodation booking",
    weight: 3,
    measure: "sla",
    targetText: "Same working day after approval",
    target: 100,
    unit: "%",
    evidence: "Approved hotel option, voucher and cancellation terms",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "A hotel is a booking line with its own check-in, check-out, room type and cost, and the cap is priced against it. But there is ONE Booking step covering every leg, so a hotel booked late on a trip whose flight went out on time cannot be told apart from one booked promptly.",
  },
  {
    code: "1.6",
    kra: "1",
    group: "",
    title: "Local transport / cab / vehicle booking",
    weight: 2,
    measure: "ratio",
    targetText: "Confirmed before required reporting time",
    target: 100,
    unit: "%",
    evidence: "Cab/vehicle confirmation and traveller acknowledgement",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "Cab is one of the five booking kinds and carries a date and a time. What is missing is the other half of the test — a REPORTING TIME to be before — and the traveller acknowledgement the sheet asks for as evidence.",
  },
  {
    code: "1.7",
    kra: "1",
    group: "",
    title: "Employee engagement travel support",
    weight: 2,
    measure: "ratio",
    targetText: "100% booking support within approved event plan and timeline",
    target: 100,
    unit: "%",
    evidence: "Approved participant list, tickets, hotel/cab confirmations",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "Section 8 of the sheet splits this cleanly — Khushi plans the activity, Tanisha books it — and asks for separate planning and booking evidence. The hub has no engagement calendar to hang a trip off, so a booking made for an event is indistinguishable from any other trip.",
  },
  {
    code: "1.8",
    kra: "1",
    group: "",
    title: "Travel tracker accuracy",
    weight: 2,
    measure: "ratio",
    targetText: "100% stage-wise update",
    target: 100,
    unit: "%",
    evidence: "Request, approval, booking, cancellation, refund and closure status",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "The one line the module answers outright. The Trip Register IS the tracker: every stage carries its own timestamp and actor, and the six statuses this line names are exactly the ones it holds. It needs no build — only for people to start using it.",
  },

  // ══ KRA 2 · Travel Policy, Cost Control & Vendor Management — 25% ═══════════
  {
    code: "2.1",
    kra: "2",
    group: "",
    title: "Travel policy compliance",
    weight: 5,
    measure: "ratio",
    targetText: "100% of bookings",
    target: 100,
    unit: "%",
    evidence: "Grade entitlement and approval workflow",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "The strongest thing in the module: band-wise entitlement shown before booking, caps applied in SQL at claim time, and a Policy Exceptions report listing every cut and every relaxation with the §7.3 evidence beside it. ⚠ It ADVISES rather than enforces while the rate card is a draft — and the card cannot be confirmed until H1, the band-to-category contradiction, is answered.",
  },
  {
    code: "2.2",
    kra: "2",
    group: "",
    title: "Fare and cost optimisation",
    weight: 5,
    measure: "ratio",
    targetText: "Lowest viable approved option presented",
    target: 100,
    unit: "%",
    evidence: "Fare comparison and deviation reason, where applicable",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "The same hole as 1.2, and the reason the two together are 10% of the sheet: without the rejected options there is no baseline to call a fare optimal against. The module does catch travel booked ABOVE the band entitlement (§16) — that is a different question from cheapest.",
  },
  {
    code: "2.3",
    kra: "2",
    group: "",
    title: "Vendor response and booking service",
    weight: 3,
    measure: "ratio",
    targetText: "At least 95% requests serviced within the required TAT",
    target: 95,
    unit: "%",
    evidence: "Vendor communication and booking timestamps",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "Airlines, hotels and bus operators exist as masters — names only. No agent, no contact, no agreed TAT, and no record of when a vendor was asked versus when they came back. The masters would need to become vendors before this could be scored.",
  },
  {
    code: "2.4",
    kra: "2",
    group: "",
    title: "Refund and credit-note recovery",
    weight: 4,
    measure: "ratio",
    targetText: "Zero avoidable loss due to missed follow-up",
    target: 100,
    unit: "%",
    evidence: "Refund register and closure evidence",
    coverage: "partial",
    source: { kind: "none" },
    gap: "Half of it is there: every booking line has a Refund received field, and the Cancelled Travel report totals what was never refunded and splits it business versus personal under §4.1. What is missing is the FOLLOW-UP — no chase state, no ageing on an unrecovered refund, so 'missed follow-up' has nothing to measure.",
  },
  {
    code: "2.5",
    kra: "2",
    group: "",
    title: "Cancellation / rescheduling control",
    weight: 2,
    measure: "sla",
    targetText: "Processed within applicable cut-off after approval",
    target: 100,
    unit: "%",
    evidence: "Cancellation/reschedule confirmation and charge record",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "Built end to end: the traveller asks, the desk unwinds, §4.1's business-or-personal reason is recorded, the charge is kept and a cancelled trip with money still open stays at the claim step rather than disappearing. The 'applicable cut-off' is the one thing not stored.",
  },
  {
    code: "2.6",
    kra: "2",
    group: "",
    title: "GST documentation",
    weight: 2,
    measure: "ratio",
    targetText: "100% applicable invoices captured",
    target: 100,
    unit: "%",
    evidence: "GST invoice and upload reference",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "A GST Input Credit register exists and apportions the tax to the settled share of each line. ⚠ The COMPANY GSTIN is not recorded — flagged as [⚠ CONFIRM with Finance] in §7.1 and §11.3 of the policy — so travellers cannot tell a hotel what number to bill and the credit is lost before it reaches the register. Scoring her on invoice capture before that is set would score her on somebody else's blocker.",
  },
  {
    code: "2.7",
    kra: "2",
    group: "",
    title: "Vendor reconciliation and issue closure",
    weight: 2,
    measure: "sla",
    targetText: "Monthly; discrepancies closed within 5 working days",
    target: 100,
    unit: "%",
    evidence: "Vendor statement, reconciliation and closure proof",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "No vendor statement, no reconciliation run, no discrepancy record. Follows from 2.3 — until a vendor is an entity with a balance, there is nothing to reconcile against.",
  },
  {
    code: "2.8",
    kra: "2",
    group: "",
    title: "Monthly Travel MIS",
    weight: 2,
    measure: "sla",
    targetText: "By the 5th of the following month",
    target: 100,
    unit: "%",
    evidence: "Budget vs actual, savings, refunds and pending issues",
    coverage: "partial",
    source: { kind: "none" },
    gap: "The CONTENT is live — Spend Summary re-cuts cost seven ways and exports to Excel. Two gaps: there is no budget in the hub, so 'budget vs actual' has no left-hand side; and nothing records that an MIS was filed, so the by-the-5th deadline cannot be timed.",
  },

  // ══ KRA 3 · Petrol Card, Conveyance & Travel Reimbursement — 20% ═══════════
  {
    code: "3.1",
    kra: "3",
    group: "",
    title: "Petrol card monthly verification",
    weight: 3,
    measure: "sla",
    targetText: "By the 1st of every month",
    target: 100,
    unit: "%",
    evidence: "Fuel portal status and monthly checklist",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "Nothing in the hub holds a petrol card. Not in Travel Desk, not in Assets, not in HR. Lines 3.1 to 3.4 and 3.8 are 13% of this sheet and none of them has anywhere to live.",
  },
  {
    code: "3.2",
    kra: "3",
    group: "",
    title: "Petrol card utilisation review",
    weight: 3,
    measure: "ratio",
    targetText: "Weekly",
    target: 100,
    unit: "%",
    evidence: "Utilisation report and exception record",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "See 3.1 — no petrol card exists in the hub.",
  },
  {
    code: "3.3",
    kra: "3",
    group: "",
    title: "Fuel reconciliation",
    weight: 4,
    measure: "sla",
    targetText: "By the 5th of the following month",
    target: 100,
    unit: "%",
    evidence: "Fuel statement matched with approved logs",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "See 3.1. The largest single unhoused line on the sheet.",
  },
  {
    code: "3.4",
    kra: "3",
    group: "",
    title: "Approved limit increase processing",
    weight: 2,
    measure: "sla",
    targetText: "Within 1 working day of approval",
    target: 100,
    unit: "%",
    evidence: "Approved request and updated limit evidence",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "See 3.1 — no card, so no limit to raise.",
  },
  {
    code: "3.5",
    kra: "3",
    group: "",
    title: "Travel and conveyance claim verification",
    weight: 3,
    measure: "sla",
    targetText: "100% valid and approved claims checked within 2 working days",
    target: 100,
    unit: "%",
    evidence: "Bills, approval and verification checklist",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "⚠ A ROLE MISMATCH, not a missing feature. The hub HAS this step, twice over — Claim Approval and Finance Verification, both SLA'd — but it routes them to the traveller's reporting manager and to Finance, never to the travel desk. Either the sheet or the routing is wrong, and somebody has to say which before Tanisha is scored on a step she cannot open.",
  },
  {
    code: "3.6",
    kra: "3",
    group: "",
    title: "Submission to Accounts",
    weight: 2,
    measure: "sla",
    targetText: "Within applicable payroll/accounts cut-off",
    target: 100,
    unit: "%",
    evidence: "Complete claim file and submission timestamp",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "Settlement records the mode — payroll deduction, NEFT, adjusted against the next advance — and says outright that nothing is written to Tally or payroll, by design. So there is no submission event to time, and the cut-off is not stored.",
  },
  {
    code: "3.7",
    kra: "3",
    group: "",
    title: "Duplicate / unsupported claim prevention",
    weight: 2,
    measure: "ratio",
    targetText: "Zero duplicate or unsupported claims processed",
    target: 100,
    unit: "%",
    evidence: "Reconciliation and exception record",
    coverage: "partial",
    source: { kind: "none" },
    gap: "UNSUPPORTED is covered: every claim line carries a receipt flag, self-declared conveyance is capped separately under §10, and §11.2 refuses a second advance while one is unreconciled. DUPLICATE is not — nothing compares a claim line against another line, another trip, or a petrol-card transaction.",
  },
  {
    code: "3.8",
    kra: "3",
    group: "",
    title: "Monthly petrol card and reimbursement MIS",
    weight: 1,
    measure: "sla",
    targetText: "By the 5th of the following month",
    target: 100,
    unit: "%",
    evidence: "Usage, claims, exceptions and pending closure report",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "Half of it follows 3.1 (no card). The reimbursement half is covered by Spend Summary and Policy Exceptions, but as with 2.8 nothing records that an MIS was filed.",
  },

  // ══ KRA 4 · Orange Hub FMS Task Management — 20% ═══════════════════════════
  {
    code: "4.1",
    kra: "4",
    group: "",
    title: "Tasks completed within TAT",
    weight: 10,
    measure: "sla",
    targetText: "Minimum 95%",
    target: 95,
    unit: "%",
    evidence: "Due date versus final approval timestamp",
    coverage: "partial",
    source: { kind: "kpiFacts", module: TASKS, rowKeys: [], basis: "onTimeOfDone" },
    gap: "⚠ THE BIGGEST LINE ON THE SHEET, AND IT CANNOT SEE HER REAL JOB. This scores live off kpi_facts — but the nightly run covers nine modules and travel-desk is not one of them, so every trip Tanisha books, every advance she chases and every cancellation she unwinds is invisible to the figure that carries 10% of her appraisal. Adding travel-desk to the run is the single highest-value change on this page.",
  },
  {
    code: "4.2",
    kra: "4",
    group: "",
    title: "First-time-right completion",
    weight: 4,
    measure: "ratio",
    targetText: "Minimum 90%",
    target: 90,
    unit: "%",
    evidence: "Accepted without avoidable rework",
    coverage: "partial",
    source: { kind: "none" },
    gap: "kpi_facts carries a `revised` flag per row, which is exactly this measurement — but the lab reads that table through two bases only, done-of-given and on-time-of-done, and neither exposes it. A third basis would turn this line on without any new data.",
  },
  {
    code: "4.3",
    kra: "4",
    group: "",
    title: "Task acknowledgement",
    weight: 2,
    measure: "sla",
    targetText: "Same working day",
    target: 100,
    unit: "%",
    evidence: "Acknowledgement timestamp",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "No acknowledgement event reaches kpi_facts from any module, so there is nothing to time. The same gap as 1.1, one layer down.",
  },
  {
    code: "4.4",
    kra: "4",
    group: "",
    title: "Completion evidence",
    weight: 3,
    measure: "ratio",
    targetText: "100% of completed tasks",
    target: 100,
    unit: "%",
    evidence: "Required file, report, booking proof or system reference",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "Attachments exist all over the hub — tickets, receipts, hotel vouchers — but nothing counts whether a completed item carried one. kpi_facts records that a step was done, not what was attached to it.",
  },
  {
    code: "4.5",
    kra: "4",
    group: "",
    title: "Risk escalation before SLA breach",
    weight: 1,
    measure: "ratio",
    targetText: "100% of identified at-risk tasks",
    target: 100,
    unit: "%",
    evidence: "Escalation timestamp, reason and revised action date",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "There is no escalation act anywhere in the hub — a step is on time or it is late, and nothing sits between. Putting a trip on hold with a reason is the nearest thing and is not the same event.",
  },

  // ══ KRA 5 · Training & Development — 5% ════════════════════════════════════
  {
    code: "5.1",
    kra: "5",
    group: "",
    title: "Assigned training attendance",
    weight: 2,
    measure: "ratio",
    targetText: "100%",
    target: 100,
    unit: "%",
    evidence: "Training attendance record",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "Learning & Development is built — attendance is marked per nominee, present or absent, and the register is closed before anything else opens. It has not reached the live hub yet.",
  },
  {
    code: "5.2",
    kra: "5",
    group: "",
    title: "Assignment / action plan submission",
    weight: 2,
    measure: "sla",
    targetText: "Within assigned timeline",
    target: 100,
    unit: "%",
    evidence: "Submission timestamp",
    coverage: "not-released",
    source: { kind: "none" },
    gap: "Same module. The assignment carries a due date and the submission is stamped against it — on-time is the whole of L&D's assessment, by decision.",
  },
  {
    code: "5.3",
    kra: "5",
    group: "",
    title: "Learning implementation",
    weight: 1,
    measure: "judgement",
    targetText: "Minimum 1 validated improvement per quarter",
    target: 100,
    unit: "%",
    evidence: "Evidence and reporting manager validation",
    coverage: "judgement",
    source: { kind: "none" },
    gap: "The sheet's own rule — a revised checklist, a booking template, a cost-saving control — is a manager's verdict on whether something got better. No system can answer it, and it is right that none tries.",
  },

  // ══ KRA 6 · Attendance, Behaviour & Professional Conduct — 5% ══════════════
  {
    code: "6.1",
    kra: "6",
    group: "",
    title: "Attendance and punctuality",
    weight: 2.5,
    measure: "ratio",
    targetText: "Minimum 75% attendance; adherence to attendance policy",
    target: 75,
    unit: "%",
    evidence: "Verified attendance record",
    coverage: "no-data",
    source: { kind: "none" },
    gap: "There is no attendance system in Orange One — no punches, no leave balance, no roster. This figure comes from outside the hub and always will until one is built. ⚠ The sheet makes it a cliff: below 75% this component scores zero outright.",
  },
  {
    code: "6.2",
    kra: "6",
    group: "",
    title: "Professional behaviour",
    weight: 1,
    measure: "judgement",
    targetText: "Courteous, factual and solution-oriented conduct",
    target: 100,
    unit: "%",
    evidence: "Factual manager remark / documented incident, if any",
    coverage: "judgement",
    source: { kind: "none" },
    gap: "A manager's remark, by design. The sheet requires a factual reference for any deduction, which is the right guard.",
  },
  {
    code: "6.3",
    kra: "6",
    group: "",
    title: "Ownership and accountability",
    weight: 0.5,
    measure: "judgement",
    targetText: "Own errors; escalate risks before deadlines are missed",
    target: 100,
    unit: "%",
    evidence: "Task and escalation records",
    coverage: "judgement",
    source: { kind: "none" },
    gap: "The evidence column asks for escalation records, which do not exist (see 4.5). Until they do, this is entirely a judgement.",
  },
  {
    code: "6.4",
    kra: "6",
    group: "",
    title: "Communication and responsiveness",
    weight: 0.5,
    measure: "judgement",
    targetText: "Acknowledge internal requests within the same working day",
    target: 100,
    unit: "%",
    evidence: "Communication timestamps",
    coverage: "judgement",
    source: { kind: "none" },
    gap: "Trip comments are timestamped, but a comment is not an acknowledgement of a request and most travel is asked for by phone or in person. Scoring this off the hub would measure who types, not who answers.",
  },
  {
    code: "6.5",
    kra: "6",
    group: "",
    title: "Confidentiality and coordination",
    weight: 0.5,
    measure: "judgement",
    targetText: "Protect employee, travel and expense data; coordinate effectively",
    target: 100,
    unit: "%",
    evidence: "Access records / documented manager review",
    coverage: "judgement",
    source: { kind: "none" },
    gap: "⚠ Worth a note rather than a score: as of 24-09-2026 being named on ANY Travel Desk step grants sight of EVERY trip in the company, Tanisha's included. She is being asked to protect data the hub hands to six people wholesale. That is a policy question, not a performance one.",
  },
];

export const tanishaFramework: Framework = {
  id: "tanisha-travel-desk-2026",
  role: "HR Executive — Travel Desk",
  source:
    "Tanisha_Tikde_Final_Revised_KRA_KPI_Travel_Desk_2026.docx — \"FINAL REVISED KRA & KPI FRAMEWORK · Travel Desk Focus\". " +
    "⚠ The document's summary table and its detailed sections disagree on two KRA weights " +
    "(Travel/Ticketing 30% vs 25%, Orange Hub FMS 15% vs 20%). The detail is taken here, because each " +
    "detailed section's own KPI weights add up to it. HR has to confirm which is right.",
  kras: [
    { code: "1", title: "Travel, Ticketing, Visa & Hotel Booking", weight: 25 },
    { code: "2", title: "Travel Policy, Cost Control & Vendor Management", weight: 25 },
    { code: "3", title: "Petrol Card, Conveyance & Travel Reimbursement", weight: 20 },
    { code: "4", title: "Orange Hub FMS Task Management", weight: 20 },
    { code: "5", title: "Training & Development", weight: 5 },
    { code: "6", title: "Attendance, Behaviour & Professional Conduct", weight: 5 },
  ],
  lines,
};
