import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Card from "@/shared/components/ui/Card";
import Button from "@/shared/components/ui/Button";
import QueueTable from "@/shared/components/ui/QueueTable";
import type { QueueColumn } from "@/shared/components/ui/QueueTable";
import KpiRow from "@/shared/components/dashboard/KpiRow";
import type { KpiTile } from "@/shared/components/dashboard/KpiRow";
import { formatDate, formatDateTime } from "@/shared/lib/time";
import {
  useMasterSnapshot,
  totalsOf,
  sinceLabel,
  lastActivitySort,
  STATE_LABEL,
} from "../data/snapshot";
import type { ModuleSnapshot, ModuleState } from "../data/snapshot";
import { downloadSnapshotPdf } from "../lib/exportSnapshotPdf";
import { useAccessMatrix, fetchAccessMatrix, accessMatrixKey } from "../lib/accessMatrix";
import UserAccess from "./UserAccess";
import Tabs from "@/shared/components/ui/Tabs";
import { useQueryClient } from "@tanstack/react-query";

/**
 * The Master Report — one row per module, answering "is this being used?".
 *
 * WHY EVERY MODULE SHOWS, EVEN ONES THE VIEWER DOESN'T OPERATE
 *   The FMS Control Center filters its rows by hasModule(), because a
 *   coordinator clicking through to a queue they lack would hit Access Denied.
 *   This screen is the opposite case on purpose: the whole question is "which of
 *   our modules are dead", and hiding the dead ones from the person who decides
 *   what to build next would defeat it. The grant for `master-report` IS the
 *   permission, and the RPC returns counts only — never a row of anyone's data.
 */

const STATE_STYLE: Record<ModuleState, string> = {
  active: "bg-[#E8F5EC] text-[#0F7A45] border-[#bfe3cd]",
  quiet: "bg-[#FDF3E2] text-[#9A6512] border-[#f0dcb4]",
  dormant: "bg-[#FDECEC] text-[#B3322F] border-[#f3c9c8]",
  // Deliberately neutral, not red: "tracking" is an absence of evidence, and
  // colouring it like dormant would make it read as the verdict it isn't.
  tracking: "bg-[#EEF2F8] text-[#4A5B75] border-[#cfd9e8]",
  error: "bg-page text-grey border-line",
};

function StateChip({ state }: { state: ModuleState }) {
  return (
    <span
      className={`inline-block rounded-full border px-2.5 py-[3px] text-[11px] font-bold uppercase tracking-wide ${STATE_STYLE[state]}`}
    >
      {STATE_LABEL[state]}
    </span>
  );
}

/** An em dash, for a number that is structurally absent rather than zero. */
const Dash = () => <span className="text-grey-2/60">&mdash;</span>;

export default function MasterReport() {
  const { data, isLoading, error, refetch, isFetching } = useMasterSnapshot(30);
  const [pdfBusy, setPdfBusy] = useState(false);
  const [tab, setTab] = useState<"modules" | "access">("modules");
  const queryClient = useQueryClient();
  // The access matrix is a second round trip, so it is not fetched until the tab
  // is opened — a director who only ever reads the module summary never pays for it.
  const access = useAccessMatrix(tab === "access");

  const modules = data?.modules ?? [];
  const totals = useMemo(() => totalsOf(modules), [modules]);

  const tiles: KpiTile[] = [
    {
      key: "new",
      label: "New today",
      value: totals.newToday,
      // Recurring tasks are generated by cron at 06:00. Folding them into this
      // number made it read as 66 people working when it was one person and a
      // scheduled job, so the machine's share is named rather than hidden.
      hint: totals.newTodaySystem
        ? `Entered by people · ${totals.newTodaySystem} more auto-generated`
        : "Entered by people since midnight IST",
    },
    { key: "open", label: "Open items", value: totals.open, hint: "Across modules that track a status" },
    {
      key: "overdue",
      label: "Overdue",
      value: totals.overdue,
      tone: totals.overdue > 0 ? "red" : undefined,
      hint: "Past their due date (where one is stored)",
    },
    {
      key: "opened",
      label: "Opened today",
      // The one number that answers "which modules are actually being used" for
      // apps people READ rather than write to — an entry count cannot.
      value: `${totals.openedToday} of ${modules.length}`,
      hint: "Modules someone opened since midnight IST",
    },
    {
      key: "dormant",
      label: "Dormant",
      value: totals.dormant,
      tone: totals.dormant > 0 ? "red" : undefined,
      hint:
        totals.tracking > 0
          ? `No activity in ${data?.dormantAfterDays ?? 7} days · ${totals.tracking} still being measured`
          : `No activity in ${data?.dormantAfterDays ?? 7} days`,
    },
  ];

  const columns: QueueColumn<ModuleSnapshot>[] = [
    {
      key: "module",
      header: "Module",
      alwaysVisible: true,
      sortValue: (r) => r.label,
      filter: { kind: "text", get: (r) => r.label },
      exportValue: (r) => r.label,
      cell: (r) => (
        <span className="inline-block">
          {r.detailPath ? (
            <Link to={r.detailPath} className="font-semibold text-navy hover:text-orange">
              {r.label}
            </Link>
          ) : (
            <span className="font-semibold text-navy">{r.label}</span>
          )}
          {r.usageFromVisits && (
            <span
              className="block text-[11px] text-grey-2"
              title="Nothing is entered here — this module is judged on how many people open it"
            >
              view-only · judged on opens
            </span>
          )}
        </span>
      ),
    },
    {
      key: "state",
      header: "State",
      align: "left",
      sortValue: (r) => r.state,
      // Searchable multi-value picker, per the house rule — never a native select.
      filter: { kind: "select", get: (r) => STATE_LABEL[r.state] },
      exportValue: (r) => STATE_LABEL[r.state],
      cell: (r) => <StateChip state={r.state} />,
    },
    {
      key: "newToday",
      header: "Created today",
      align: "right",
      sortValue: (r) => r.newToday,
      exportValue: (r) => r.newToday,
      cell: (r) => (
        <span>
          {r.newToday ? <span className="font-semibold text-navy">{r.newToday}</span> : <Dash />}
          {r.newTodaySystem > 0 && (
            <span className="ml-1 text-[11.5px] text-grey-2" title="Generated automatically, not entered by a person">
              +{r.newTodaySystem} auto
            </span>
          )}
        </span>
      ),
    },
    {
      key: "new7d",
      header: "Created (7 days)",
      align: "right",
      sortValue: (r) => r.new7d,
      exportValue: (r) => r.new7d,
      cell: (r) => (r.new7d ? r.new7d : <Dash />),
    },
    {
      key: "open",
      header: "Open now",
      align: "right",
      sortValue: (r) => (r.tracksStatus ? r.open : -1),
      exportValue: (r) => (r.tracksStatus ? r.open : ""),
      cell: (r) => (r.tracksStatus ? <span className="font-semibold text-navy">{r.open}</span> : <Dash />),
    },
    {
      key: "overdue",
      header: "Overdue",
      align: "right",
      sortValue: (r) => (r.tracksDue ? r.overdue : -1),
      exportValue: (r) => (r.tracksDue ? r.overdue : ""),
      cell: (r) =>
        !r.tracksDue ? (
          // The FMS modules derive due dates in TypeScript, so SQL cannot give a
          // true overdue for them. A dash says "not measurable here"; a 0 would
          // have said "nothing is late", which is a different and false claim.
          <span className="text-grey-2/60" title="No stored due date — see Open >7d, or the FMS Control Center for step due dates">
            &mdash;
          </span>
        ) : r.overdue > 0 ? (
          <span className="font-semibold text-ryg-red">{r.overdue}</span>
        ) : (
          <span className="text-grey">0</span>
        ),
    },
    {
      key: "ageing",
      header: "Open over 7 days",
      align: "right",
      defaultHidden: true,
      sortValue: (r) => (r.tracksStatus ? r.ageingOpenGt7d : -1),
      exportValue: (r) => (r.tracksStatus ? r.ageingOpenGt7d : ""),
      cell: (r) =>
        !r.tracksStatus ? (
          <Dash />
        ) : r.ageingOpenGt7d > 0 ? (
          <span className="text-navy" title={`Oldest open item was created ${r.oldestOpenDays} days ago`}>
            {r.ageingOpenGt7d}
          </span>
        ) : (
          <Dash />
        ),
    },
    {
      key: "users",
      header: "People active (7 days)",
      align: "right",
      sortValue: (r) => r.activeUsers7d,
      exportValue: (r) => r.activeUsers7d,
      cell: (r) => (r.activeUsers7d ? r.activeUsers7d : <Dash />),
    },
    {
      key: "opened",
      header: "People opened (7 days)",
      align: "right",
      sortValue: (r) => r.visitors7d,
      exportValue: (r) => r.visitors7d,
      // Distinct people, not raw opens: one person refreshing all day is not
      // adoption. The repeat count rides along in the tooltip.
      cell: (r) =>
        r.visitors7d ? (
          <span title={`${r.opens7d} opens in total · ${r.visitorsToday} today`}>{r.visitors7d}</span>
        ) : (
          <Dash />
        ),
    },
    {
      key: "last",
      header: "Last activity",
      align: "right",
      sortValue: lastActivitySort,
      exportValue: (r) => (r.lastSignalAt ? formatDateTime(r.lastSignalAt) : "never"),
      // The relative label stays primary — it is what makes a stale module jump
      // out of the column — with the real date beneath it, so a reader has
      // something to quote and file against.
      //
      // The COMBINED signal (entry or open), because for a view-only module an
      // open is the only thing that ever happens; showing its last entry would
      // permanently misreport an app in daily use.
      cell: (r) => {
        const at = r.lastSignalAt;
        const openWasLatest = !!r.lastVisitAt && r.lastVisitAt === at;
        return (
          <span className="inline-block text-right">
            <span className={at ? "text-grey" : "text-grey-2/70"}>{sinceLabel(at)}</span>
            {at && (
              <span className="block text-[11.5px] text-grey-2">
                {formatDate(at.slice(0, 10))}
                {openWasLatest && (
                  <span className="ml-1" title="The most recent thing here was someone opening it">
                    · opened
                  </span>
                )}
              </span>
            )}
          </span>
        );
      },
    },
    {
      key: "total",
      header: "Total entries",
      align: "right",
      defaultHidden: true,
      sortValue: (r) => r.total,
      exportValue: (r) => r.total,
      cell: (r) => r.total,
    },
  ];

  const errored = modules.filter((m) => m.state === "error");

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-[22px] font-bold text-navy">Master Report</h1>
          <p className="mt-1 max-w-3xl text-[13.5px] text-grey-2">
            One row per module: what people created, what is still open, who opened it, and when anyone last
            touched it. <strong>Dormant</strong> means nothing has happened in {data?.dormantAfterDays ?? 7} days —
            a module that exists but is not being used. <strong>Created today</strong> counts entries made by a
            person; anything a scheduled job generated is shown beside it as <em>auto</em>. A few modules are
            read-only — nothing is ever entered into them — so they are judged on{" "}
            <strong>People opened</strong> instead, and are marked <em>view-only</em>. For step-by-step due dates,
            open the{" "}
            <Link to="/fms-control-center" className="text-orange hover:underline">
              FMS Control Center
            </Link>
            .
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={() => void refetch()} disabled={isFetching}>
            {isFetching ? "Refreshing…" : "Refresh"}
          </Button>
          <Button
            variant="outline"
            size="sm"
            disabled={!data || pdfBusy}
            onClick={async () => {
              if (!data) return;
              setPdfBusy(true);
              try {
                // The PDF always carries BOTH sections, whichever tab is open, so
                // the downloaded document is the whole report rather than
                // whatever the reader happened to be looking at. The matrix is
                // fetched on demand; react-query serves it from cache if the
                // User access tab has already been opened this session.
                const matrix = await queryClient.fetchQuery({
                  queryKey: accessMatrixKey,
                  queryFn: fetchAccessMatrix,
                  staleTime: 5 * 60_000,
                });
                await downloadSnapshotPdf(data, matrix);
              } finally {
                setPdfBusy(false);
              }
            }}
          >
            {pdfBusy ? "Building…" : "Download PDF"}
          </Button>
        </div>
      </div>

      <Tabs
        tabs={[
          { key: "modules", label: "Module activity", count: modules.length },
          { key: "access", label: "User access", count: access.data?.rows.length },
        ]}
        active={tab}
        onChange={(k) => setTab(k as "modules" | "access")}
      />

      {tab === "access" && <UserAccess />}

      {tab === "modules" && isLoading && (
        <Card className="p-6 text-[14px] text-grey">Loading the snapshot…</Card>
      )}

      {tab === "modules" && error && (
        <Card className="border-ryg-red/30 bg-[#FDECEC] p-4 text-[13.5px] text-[#B3322F]">
          Could not load the snapshot: {(error as Error).message}
        </Card>
      )}

      {tab === "modules" && data && (
        <>
          <KpiRow tiles={tiles} />

          {errored.length > 0 && (
            <Card className="border-ryg-red/30 bg-[#FDECEC] p-4 text-[13px] text-[#B3322F]">
              <b>
                {errored.length} module{errored.length > 1 ? "s" : ""} could not be counted.
              </b>{" "}
              Usually a table renamed since the report was configured. The rest of the report is unaffected.
              <ul className="mt-1.5 list-disc pl-5">
                {errored.map((m) => (
                  <li key={m.appId}>
                    {m.label}: {m.error}
                  </li>
                ))}
              </ul>
            </Card>
          )}

          <Card className="p-4">
            <QueueTable
              rows={modules}
              rowKey={(r) => r.appId}
              columns={columns}
              rowsLabel="modules"
              initialSort={{ key: "newToday", dir: "desc" }}
              emptyTitle="No modules configured"
              emptyMessage="Add rows to master_report_modules to populate this report."
              exportName="Master_Report"
              exportTitle="Orange One — module snapshot"
              exportNotes={[
                `Generated ${data.generatedAt ? formatDateTime(data.generatedAt) : ""}.`,
                `"Dormant" = no activity in ${data.dormantAfterDays} days. "Quiet" = worked, but no new entries in ${data.windowDays} days.`,
                "New today counts entries made by PEOPLE. Automatically generated rows (e.g. recurring tasks) are shown separately as '+N auto'.",
                "Overdue = open items past a stored due date. Blank where the module has no stored due date — its step due dates are computed in the app, so see the FMS Control Center for those.",
                "Open >7d = open items CREATED more than 7 days ago. It is an age, not a deadline.",
                "Open and Overdue are blank for modules with no workflow status (Leads, receivables follow-ups).",
                "People opened = distinct people who opened the module in the last 7 days. Modules marked view-only (e.g. the Outstanding Dashboard) hold no entries at all — their data is produced elsewhere — so this, not a row count, is their usage signal.",
                data.visitsSince
                  ? `Opens have been counted since ${formatDateTime(data.visitsSince)}. "Tracking" means a view-only module has not been watched long enough to be called dormant.`
                  : "Open tracking is not yet configured on this database.",
              ]}
              columnPicker={{ storageKey: "master-report-columns" }}
            />
          </Card>

          <p className="text-[12px] text-grey-2">
            Snapshot taken {data.generatedAt ? formatDateTime(data.generatedAt) : "just now"}. Counts come from the
            server, so this page and the daily email always agree.
          </p>
        </>
      )}
    </div>
  );
}
