-- OCPI-14 · Phase 2 — the master, refreshed from the client's 01-09 sheet.
--
-- Source: Misc/Bushra Reports/OCPI/OCPI Machine Templates - 01-09.xlsx, 28 rows.
-- Every UPDATE below was GENERATED from that file (scratchpad/gen_phase2.cjs),
-- not typed, and the full 28-row before/after diff is recorded in
-- supabase/backups/ocpi-14/0.3-sheet-vs-database.md.
--
-- ⚠ THIS FILE FILLS THE PHASE 1 COLUMNS AND CORRECTS THE OLD ONES. It still
--   changes NO behaviour: the branch rules do not read the category yet, and
--   fms_ocpi_write_oc still gates on needs_dryer / opt_external_centering. What
--   it does is make those two agree with the category, so that when Phase 3
--   switches the gate over, the new rule and the old rule already say the same
--   thing on 27 of 28 machines and are merely WIDER on the 28th.
--
-- ⚠ ROLLBACK: schema ocpi14_backup holds an exact copy of all four master
--   tables taken before this ran. `select ocpi14_backup.restore('machines')`
--   and the same for machine_categories / head_types / machine_head_types.
--   Rehearsed on live data 01-Sep-2026: mutated three rows, restored, and every
--   column of all 28 matched the snapshot again.
--
-- ── TWO PLACES THIS DELIBERATELY DOES NOT COPY THE SHEET ─────────────────────
--
-- 1. The sheet spells the Ricoh head "RICHO GEN 6". That is a typo of a
--    manufacturer's name, the master already has it right, and this string
--    PRINTS ON A CUSTOMER'S CONTRACT. Stored as "RICOH GEN 6".
-- 2. The sheet writes the same period as both "12 Month" and "12 Months" in one
--    column. Normalised to the plural, so two contracts do not word the same
--    warranty differently.
--
--    Everything else is the sheet verbatim.

begin;

-- ── 2.1 · POD, and what each category makes the form ask ────────────────────
--
-- POD is the sheet's fourth machine type and the master has never had it; Label
-- Printer and Book Printer have sat with NO category at all since they were
-- created. This also answers OCPI-5's open question 0.1, which asked where the
-- two "JAY" machines belong.
--
-- sort_order 25 keeps "Other" last in the dropdown, where a reader expects it,
-- without renumbering a row that is already in use.

insert into public.fms_ocpi_machine_categories (name, active, sort_order)
values ('POD', true, 25)
on conflict (name) do update set active = true;

-- ⚠ TRUE ON DIRECT, FALSE EVERYWHERE ELSE — and false is written explicitly
--   rather than left null. Null reads as false in both engines, but a column
--   that is null on three rows and true on one looks unfinished; an admin
--   opening the Masters screen should see three answered questions, not three
--   blanks they might feel obliged to fill in.
update public.fms_ocpi_machine_categories
   set shows_dryer     = (name = 'Direct'),
       shows_centering = (name = 'Direct'),
       shows_extras    = (name = 'Direct');

-- ── 2.2 · JP7 IS MP5000 ────────────────────────────────────────────────────
-- Ritesh Bhai, 01-Sep-2026: a rename, not a new machine, so it is done by id
-- and every deal already quoted on it follows without a data change.
update public.fms_ocpi_machines set name = 'MP5000' where name = 'JP7';

-- ── 2.3a · the head vocabulary the sheet uses ──────────────────────────────
-- EX600 and RC are new; the other three already existed under longer names.
-- ⚠ EXISTING HEAD-TYPE ROWS ARE LEFT ALONE. fms_ocpi_deals.head_type stores
--   TEXT, so a name an old deal was quoted under has to stay readable in the
--   master even once no machine maps to it any more.
insert into public.fms_ocpi_head_types (name, active)
select v, true from unnest(array['EX600', 'I3200', 'KJ4B', 'RC', 'RICOH GEN 6']) v
on conflict (name) do update set active = true;

-- ── 2.3 · THE SHEET, AS A TABLE ────────────────────────────────────────────
--
-- All 28 rows of the client's file, in its own order, so this migration can be
-- read straight against the spreadsheet instead of against 28 separate UPDATEs.
-- Generated by scratchpad/gen_phase2b.cjs — not typed.
--
--    machine                                       category        dryer  air         centering   ink dust    chilling    machine wty  head wty     dryer wty    billing  heads
create temp table ocpi14_sheet (
  name text, category text, needs_dryer boolean,
  air text, cen text, dust text, chill text,
  mw text, hw text, dw text, billing text, heads text[]
) on commit drop;

insert into ocpi14_sheet values
  ('Homer K24'                                     , 'Direct'      , true , 'no'      , 'optional', 'optional', 'optional', '12 Months', '18 Months', '12 Months', 'LARGE FORMAT INKJET PRINTER WITH 24 HEADS WITH STD. ACCESSORIES', array['EX600','RC']),
  ('Homer K32'                                     , 'Direct'      , true , 'no'      , 'optional', 'optional', 'optional', '12 Months', '18 Months', '12 Months', 'LARGE FORMAT INKJET PRINTER WITH 32 HEADS WITH STD. ACCESSORIES', array['EX600','RC']),
  ('P8S'                                           , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', '18 Months', null       , 'LARGE FORMAT INKJET PRINTER WITH 8 HEADS WITH STD. ACCESSORIES', array['EX600','RC']),
  ('P8D'                                           , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', '18 Months', null       , 'LARGE FORMAT INKJET PRINTER WITH 8 HEADS WITH STD. ACCESSORIES', array['EX600','RC']),
  ('Kolorado Alpha 15'                             , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'SUBLIMATION PRINTER KOLORADO ALPHA 15 WITH STANDARD ACCESSORIES (LARGE FORMAT PRINTERS FOR INDUSTRIAL USE)', array['I3200']),
  ('KoloRado Alpha II — 1.8 m, 8 heads'            , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'LARGE FORMAT INKJET PRINTER WITH 8 HEADS WITH STD. ACCESSORIES', array['I3200']),
  ('KoloRado Alpha II — 1.9 m, 8 heads (OT-1908A)' , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'LARGE FORMAT INKJET PRINTER WITH 8 HEADS WITH STD. ACCESSORIES', array['I3200']),
  ('KoloRado Alpha II — 2.2 m, 8 heads'            , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'LARGE FORMAT INKJET PRINTER WITH 8 HEADS WITH STD. ACCESSORIES', array['I3200']),
  ('KoloRado Alpha 3.2 — 24 heads'                 , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'LARGE FORMAT INKJET PRINTER WITH 24 HEADS WITH STD. ACCESSORIES', array['I3200']),
  ('Pengda PD-1700XD-1000'                         , 'Other'       , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'HEAT TRANSFER MACHINE', array[]::text[]),
  ('K64'                                           , 'Direct'      , true , 'yes'     , 'optional', 'optional', 'optional', '12 Months', '18 Months', '12 Months', 'DIGITAL INKJET TEXTILE PRINTING MACHINE WITH STANDARD ACCESSORIES WITH 64 PRINTHEADS', array['EX600','RC']),
  ('MP5000'                                        , 'Direct'      , true , 'yes'     , 'optional', 'optional', 'no'      , '12 Months', '18 Months', '12 Months', null, array['EX600']),
  ('JPK'                                           , 'Direct'      , true , 'yes'     , 'optional', 'optional', 'no'      , '12 Months', '18 Months', '12 Months', null, array['KJ4B']),
  ('Mini Lario'                                    , 'Direct'      , true , 'yes'     , 'optional', 'optional', 'no'      , '12 Months', '18 Months', '12 Months', null, array['KJ4B']),
  ('Fab Pro 1I'                                    , 'Direct'      , true , 'no'      , 'no'      , 'optional', 'no'      , '12 Months', '18 Months', '12 Months', 'LARGE FORMAT INKJET PRINTER WITH 8 HEADS WITH STD. ACCESSORIES', array['RICOH GEN 6']),
  ('Fab Pro 2I'                                    , 'Direct'      , true , 'no'      , 'no'      , 'optional', 'no'      , '12 Months', '18 Months', '12 Months', null, array['RICOH GEN 6']),
  ('Fab Pro 3I'                                    , 'Direct'      , true , 'no'      , 'no'      , 'optional', 'no'      , '12 Months', '18 Months', '12 Months', null, array['RICOH GEN 6']),
  ('Position Printer'                              , 'Direct'      , true , 'no'      , 'optional', 'optional', 'no'      , '12 Months', '18 Months', '12 Months', 'POSITION PRINTER PRO', array['EX600','RC']),
  ('KoloRado Alpha 3 — 12 heads'                   , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , null, array['I3200']),
  ('Kolorado Alpha 16'                             , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , null, array['I3200']),
  ('KoloRado Alpha 3.2 — 8 heads'                  , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'LARGE FORMAT INKJET PRINTER WITH 8 HEADS WITH STD. ACCESSORIES', array['I3200']),
  ('KoloRado Alpha 3.2 — 16 heads'                 , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'LARGE FORMAT INKJET PRINTER WITH 16 HEADS WITH STD. ACCESSORIES', array['I3200']),
  ('Pengda PD-1700XD-800'                          , 'Other'       , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'HEAT TRANSFER MACHINE', array[]::text[]),
  ('Pengda PD-1800XD-800'                          , 'Other'       , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'HEAT TRANSFER MACHINE', array[]::text[]),
  ('Rocket'                                        , 'Direct'      , true , 'yes'     , 'optional', 'optional', 'optional', '12 Months', '18 Months', '12 Months', 'STANDARD DIGITAL DIRECT TO FABRIC TEXTILE PRINTING MACHINE WITH STD. ACC WITH 224 PRINTHEADS', array['EX600','RC']),
  ('Foil Machine'                                  , 'Sublimation' , false, 'no'      , 'no'      , 'no'      , 'no'      , '12 Months', null       , null       , 'FOIL JET MACHINE', array['I3200']),
  ('Label Printer'                                 , 'POD'         , false, 'no'      , 'no'      , 'no'      , 'no'      , null       , null       , null       , 'Labstar 330E Hybrid', array[]::text[]),
  ('Book Printer'                                  , 'POD'         , false, 'no'      , 'no'      , 'no'      , 'no'      , null       , null       , null       , 'DIGITAL BOOK PRINTING MACHINE', array[]::text[]);

-- Every machine in the sheet must exist in the master, and vice versa. If the
-- client adds a model to the sheet without adding it in Masters, this is where
-- it is caught -- rather than by that machine silently keeping stale answers.
do $guard$
declare v_n integer; v_names text;
begin
  select count(*), coalesce(string_agg(s.name, ', '), '') into v_n, v_names
    from ocpi14_sheet s
   where not exists (select 1 from public.fms_ocpi_machines m where m.name = s.name);
  if v_n <> 0 then raise exception 'OCPI-14: % sheet machine(s) missing from the master: %', v_n, v_names; end if;

  select count(*), coalesce(string_agg(m.name, ', '), '') into v_n, v_names
    from public.fms_ocpi_machines m
   where not exists (select 1 from ocpi14_sheet s where s.name = m.name);
  if v_n <> 0 then raise exception 'OCPI-14: % master machine(s) absent from the sheet: %', v_n, v_names; end if;
end $guard$;

update public.fms_ocpi_machines m set
  category_id            = c.id,
  needs_dryer            = s.needs_dryer,
  opt_air_blade          = s.air,
  opt_external_centering = s.cen,
  opt_ink_dust_exhauster = s.dust,
  opt_chilling_system    = s.chill,
  machine_warranty       = s.mw,
  head_warranty          = s.hw,
  dryer_warranty         = s.dw,
  -- FILLED where blank, never overwritten: the master's wording has been edited
  -- by hand since the sheet was written and that editing is not being undone.
  billing_name           = coalesce(m.billing_name, s.billing)
from ocpi14_sheet s
join public.fms_ocpi_machine_categories c on c.name = s.category
where m.name = s.name;

-- ── 2.3b · the head mapping, rebuilt ───────────────────────────────────────
--
-- 🔴 THE SHEET SAYS "EX600 or RC" AND THE FORM HAS BEEN READING IT AS "AND".
--    chooseMachine joins every mapped head with " + ", so a K64 was being quoted
--    "Homer + KATANA 600 DPI - HANGLORY" when the customer chooses ONE of two.
--    Seven machines are affected; Phase 4 turns the choice into buttons.
--
-- Deleting first is safe: fms_ocpi_deals.head_type is frozen TEXT, so no deal
-- reads this table. 22 of 28 machines change mapping here.
delete from public.fms_ocpi_machine_head_types mh
 using public.fms_ocpi_machines m, ocpi14_sheet s
 where mh.machine_id = m.id and m.name = s.name;

insert into public.fms_ocpi_machine_head_types (machine_id, head_type_id)
select m.id, h.id
  from ocpi14_sheet s
  join public.fms_ocpi_machines m on m.name = s.name
  cross join lateral unnest(s.heads) as hn(name)
  join public.fms_ocpi_head_types h on h.name = hn.name
on conflict do nothing;

-- ── 2.4 · every deal already on record gets the category it was quoted under ─
--
-- 🔴 THIS IS WHAT LETS PHASE 3 CARRY ONE RULE INSTEAD OF TWO. Without it,
--    machine_category_id is null on all 20 rows and fms_ocpi_write_oc would need
--    a permanent "if the deal has no category, fall back to the old
--    machine-driven behaviour" shim — a second rule living beside the first
--    forever, in the one function in this module where two rules disagreeing is
--    the standing hazard.
--
-- ⚠ RUN AFTER 2.2 AND 2.3, NOT BEFORE. Position Printer only became Direct a
--   few statements ago, and the two POD machines only got a category at all in
--   2.1. Back-filling first would have frozen the OLD categorisation onto every
--   deal quoted on those three machines.
--
-- A draft with no machine yet stays null, correctly: it has not been quoted
-- under anything. The RPC's coalesce() covers it until a machine is picked.

update public.fms_ocpi_deals d
   set machine_category_id = m.category_id
  from public.fms_ocpi_machines m
 where m.id = d.machine_id
   and d.machine_category_id is null;

-- ── 2.5 · Checkpoint — prove the invariant BEFORE anything reads it ──────────

do $check$
declare
  v_n integer;
  v_names text;
begin
  -- Assertion 1 · THE INVARIANT THE WHOLE CHANGE RESTS ON.
  -- "Direct has a dryer, nothing else does" must hold for every machine, or
  -- Phase 3 would hide the dryer section on a model that needs one. It did NOT
  -- hold before this file ran: Position Printer sat in Other with needs_dryer.
  select count(*), coalesce(string_agg(m.name, ', '), '')
    into v_n, v_names
    from public.fms_ocpi_machines m
    left join public.fms_ocpi_machine_categories c on c.id = m.category_id
   where coalesce(m.needs_dryer, false) is distinct from coalesce(c.shows_dryer, false);
  if v_n <> 0 then
    raise exception 'OCPI-14 assertion 1: needs_dryer disagrees with the category on % machine(s): %', v_n, v_names;
  end if;

  -- Assertion 2 · every machine has a category. Two had none until 2.1.
  select count(*) into v_n from public.fms_ocpi_machines where category_id is null;
  if v_n <> 0 then raise exception 'OCPI-14 assertion 2: % machine(s) still have no category', v_n; end if;

  -- Assertion 3 · four categories, exactly one of which opens the extra questions.
  select count(*) into v_n from public.fms_ocpi_machine_categories where active;
  if v_n <> 4 then raise exception 'OCPI-14 assertion 3: expected 4 active categories, found %', v_n; end if;
  select count(*) into v_n from public.fms_ocpi_machine_categories
   where shows_dryer and shows_centering and shows_extras;
  if v_n <> 1 then raise exception 'OCPI-14 assertion 4: expected exactly 1 category to open the extras, found %', v_n; end if;

  -- Assertion 5 · THE SEVEN MACHINES WHOSE HEAD IS A CHOICE. The sheet reads
  -- "EX600 or RC" on exactly seven models, and that "or" is the whole point of
  -- the head change — the form used to join two mapped heads with " + " and
  -- write "and" onto the deal. If this count moves, the form's ChoiceButtons
  -- appear on the wrong machines.
  select count(*) into v_n from (
    select mh.machine_id from public.fms_ocpi_machine_head_types mh
     group by mh.machine_id having count(*) > 1) x;
  if v_n <> 7 then raise exception 'OCPI-14 assertion 5: expected 7 multi-head machines, found %', v_n; end if;

  -- Assertion 6 · no machine lost its heads by accident. 23 of 28 carry one;
  -- the 3 Pengda and the 2 POD machines carry none, per the sheet.
  select count(*) into v_n from public.fms_ocpi_machines m
   where not exists (select 1 from public.fms_ocpi_machine_head_types mh where mh.machine_id = m.id);
  if v_n <> 5 then raise exception 'OCPI-14 assertion 6: expected 5 machines with no head, found %', v_n; end if;

  -- Assertion 7 · the Ricoh spelling was corrected, not copied.
  select count(*) into v_n from public.fms_ocpi_head_types where name ilike 'RICHO%';
  if v_n <> 0 then raise exception 'OCPI-14 assertion 7: the sheet''s "RICHO" typo reached the master'; end if;

  -- Assertion 8 · warranty is worded ONE way. "12 Month" and "12 Months" both
  -- appear in the sheet for the same period; two contracts must not differ.
  select count(*) into v_n from public.fms_ocpi_machines
   where machine_warranty ~ '^\d+ Month$' or head_warranty ~ '^\d+ Month$' or dryer_warranty ~ '^\d+ Month$';
  if v_n <> 0 then raise exception 'OCPI-14 assertion 8: % machine(s) carry a singular "Month"', v_n; end if;

  -- Assertion 9 · head warranty is NOT the global 18 months for everybody, which
  -- is the finding that moved warranty onto the machine in the first place.
  -- 15 of 28 models carry NO head warranty at all: 10 of the 12 sublimation
  -- machines, all 3 Pengda, and both POD printers.
  -- ⚠ P8S AND P8D ARE THE EXCEPTION, and the reason this is a count rather than
  --   a category test — they are sublimation and they DO carry 18 months. An
  --   earlier draft asserted "null on every sublimation machine" and would have
  --   failed here, correctly.
  select count(*) into v_n from public.fms_ocpi_machines where head_warranty is null;
  if v_n <> 15 then raise exception 'OCPI-14 assertion 9: expected 15 machines with no head warranty, found %', v_n; end if;

  -- Assertion 10 · every deal with a machine now knows its category.
  select count(*) into v_n from public.fms_ocpi_deals
   where machine_id is not null and machine_category_id is null;
  if v_n <> 0 then raise exception 'OCPI-14 assertion 10: % deal(s) with a machine have no category', v_n; end if;

  -- Assertion 11 · NOTHING READS ANY OF IT YET. Phase 2 must leave behaviour
  -- untouched; if a write RPC already branched on the category this file could
  -- not be applied on its own.
  select count(*) into v_n from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
     and p.proname in ('fms_ocpi_write_quotation', 'fms_ocpi_write_oc', 'fms_ocpi_save_draft')
     and pg_get_functiondef(p.oid) like '%machine_category_id%';
  if v_n <> 0 then raise exception 'OCPI-14 assertion 11: a write RPC already reads the category'; end if;
end $check$;

commit;
