/**
 * Dharmistha's Weekly Review Report, transcribed (HRREP-1, read-only).
 *
 * SOURCE: files/HR KPI KRA SOP/Dharmistha_Prajapati_Final_Updated_Weekly_Report_Insurance_ID_2026.docx
 * — "ORANGE O TEC · FINAL UPDATED WEEKLY REVIEW REPORT · Executive - HR & Admin |
 * Insurance, HROne ID and Exit Controls".
 *
 * Every `label` and `targetText` is the form's own wording, copied. `coverage`, `source`
 * and `gap` are ours: they are what the hub can fill, read off the live database on
 * 28-09-2026.
 *
 * ⚠ NOTHING TYPED INTO THIS REPORT IS SAVED. Same as Saloni's — every hand-typed box
 *   stays in one browser and reaches no table, no colleague and no report. Whether a
 *   filled weekly report should become a RECORD is an open question with HR (logged in
 *   WORKLIST.md → Waiting for, 23-09-2026), and it matters more on this form than on
 *   Saloni's: section K of her own KRA sheet scores her on "100% assigned reports
 *   submitted on time", and a report that cannot record its own submission cannot
 *   evidence that line.
 *
 * ── The repeating registers ──────────────────────────────────────────────────
 * Seven sections end in a blank grid — a row per joiner, per claim, per request, per
 * dispatch. A grid is not a box, so each is modelled as ONE field describing the
 * register, banded on whether the hub holds the rows that would fill it. That keeps the
 * coverage meter honest: an eight-column table nobody can fill is one gap, not eight.
 *
 * ── What the hub fills ───────────────────────────────────────────────────────
 * Section D is General Purchase and fills itself. Section J is Task Management and
 * fills itself. Everything else is either a register that does not exist (insurance,
 * PF/ESIC, courier, petty cash, CRM routing), a module nobody has started using
 * (Employee Exit), or one that has not shipped (Help Desk).
 */
import type { ReportForm, FieldDef } from "./types";

const fields: FieldDef[] = [
  /* ═══ H · Report header ═══════════════════════════════════════════════════ */
  {
    code: "H.1",
    section: "H",
    block: "Report header",
    label: "Employee",
    targetText: "Dharmistha Prajapati",
    kind: "text",
    coverage: "live",
    source: "profiles + designations — the chosen person's own name and designation.",
  },
  {
    code: "H.2",
    section: "H",
    block: "Report header",
    label: "Reporting To",
    targetText: "Assistant Manager - HR & Admin / HR-Admin Head",
    kind: "text",
    coverage: "live-partial",
    source: "user_hods — the reporting HOD of the chosen person.",
    gap: 'The directory has no "Assistant Manager - HR & Admin" designation at all, and records the HR Head as Riya Kumari. The report prints the hub\'s name and says so rather than quietly printing the form\'s.',
  },
  {
    code: "H.3",
    section: "H",
    block: "Report header",
    label: "Week / Period",
    targetText: "________________ to ________________",
    kind: "date",
    coverage: "live",
    source: "The week chosen on this page. ISO Monday–Sunday, the same week the live KRA / KPI Scorecard uses.",
  },
  {
    code: "H.4",
    section: "H",
    block: "Report header",
    label: "Report Date",
    targetText: "________________",
    kind: "date",
    coverage: "live",
    source: "Today, in India.",
  },
  {
    code: "H.5",
    section: "H",
    block: "Report header",
    label: "Overall Status",
    targetText: "Green / Amber / Red",
    kind: "text",
    coverage: "narrative",
    source: "A judgement about the week, by design.",
  },
  {
    code: "H.6",
    section: "H",
    block: "Report header",
    label: "Next Review",
    targetText: "________________",
    kind: "date",
    coverage: "no-table",
    source: "Nothing schedules a next review.",
    gap: "There is no review calendar in the hub. It would be one date on one row — the smallest build on this form, and the same gap Saloni's report has.",
  },

  /* ═══ DASH · Executive KPI dashboard ══════════════════════════════════════ */
  {
    code: "DASH.1",
    section: "DASH",
    block: "Executive KPI dashboard — final 100% weightage",
    label: "Weekly status / remarks, per KRA",
    targetText: "Twelve KRAs with their weights, one status line each; total 100%",
    kind: "text",
    coverage: "live-partial",
    source: "The twelve KRAs and their weights come from her framework sheet; the two measurable ones carry a live figure.",
    gap: "Only KRA 4 (General Purchase) and KRA 10 (Task Management) carry a number the hub can put in this strip — 25% of the sheet. The other ten rows are a remark somebody types.",
  },

  /* ═══ A · New joiner onboarding & employee master management — 15% ════════ */
  {
    code: "A.1",
    section: "A",
    block: "Controls",
    label: "HROne ID activation and department/manager mapping",
    targetText: "Within 48 hours of DOJ",
    kind: "percent",
    coverage: "no-table",
    source: "HROne. The hub holds no HROne id and no activation timestamp.",
    gap: "HROne is a separate system the hub does not touch. Filling this box means HROne exposing the dates, or somebody keying them in twice.",
  },
  {
    code: "A.2",
    section: "A",
    block: "Controls",
    label: "Email, digital signature and applicable ID/access requests",
    targetText: "Within 48 hours of DOJ",
    kind: "percent",
    coverage: "no-table",
    source: "Nothing records an official email being created or a digital signature being issued.",
    gap: "The onboarding checklist has ten items and none of them is the email or the signature. One more check on fms_hr_onboarding_items would do it, and it is a master row, not a build.",
  },
  {
    code: "A.3",
    section: "A",
    block: "Controls",
    label: "Documents, file, asset request and induction kit",
    targetText: "Complete within 7 working days of DOJ",
    kind: "percent",
    coverage: "live-partial",
    source: "fms_hr_onboardings + fms_hr_onboarding_checks — the Onboarding step and its ten checks, with the module's own SLA.",
    gap: 'Documents, filing and the induction are all real checks and are being ticked (40 across 4 joiners). The ASSET REQUEST is the odd one out: it has a home in General Purchase and no onboarding row links to one, so "asset requested" and "asset delivered" cannot be joined.',
  },
  {
    code: "A.4",
    section: "A",
    block: "Controls",
    label: "Passport process handover to Saloni",
    targetText: "As per ownership workflow",
    kind: "text",
    coverage: "no-table",
    source: "Nothing records a handover of the passport process.",
    gap: "A one-line responsibility transfer with no table behind it. Tanisha's sheet has the same shape — a Responsibility Boundary matrix that exists only on paper.",
  },
  {
    code: "A.5",
    section: "A",
    block: "Joiner register",
    label: "Employee · DOJ · HROne activation · Email/ID request · Documents/File · Asset/Kit · Completion date · Status",
    targetText: "One row per joiner this week",
    kind: "count",
    coverage: "live-partial",
    source: "fms_hr_onboardings — joining_date, the ten checks, induction_on and completed_at.",
    gap: "Six of the eight columns fill themselves. HROne activation and the email/ID request are the two that cannot — see A.1 and A.2.",
  },

  /* ═══ B · Compliance, registration & insurance — 10% ══════════════════════ */
  {
    code: "B.1",
    section: "B",
    block: "Sub-KPIs",
    label: "PF / ESIC registration coordination",
    targetText: "5% · Within 3 working days of joining",
    kind: "percent",
    coverage: "no-table",
    source: "Nothing in the hub holds PF or ESIC registration.",
    gap: 'The only PF/ESIC rows anywhere are recurring Task Management tasks for paying the monthly challan, which belong to Finance. A joiner\'s registration is a different event and has no table.',
  },
  {
    code: "B.2",
    section: "B",
    block: "Sub-KPIs",
    label: "Insurance addition and deletion management",
    targetText: "2% · Addition within 3 working days of DOJ; deletion within 2 working days of LWD",
    kind: "percent",
    coverage: "no-table",
    source: "Nothing holds employee insurance.",
    gap: "⚠ Asset Maintenance tracks insurance POLICIES — for vehicles and buildings, with renewal reminders. It is not employee mediclaim and must not be read as it. No dependants, no endorsement, no insurer or TPA anywhere.",
  },
  {
    code: "B.3",
    section: "B",
    block: "Sub-KPIs",
    label: "Insurance claims intimation and follow-up",
    targetText: "3% · Same-working-day intimation; weekly follow-up until processed/settled",
    kind: "percent",
    coverage: "no-table",
    source: "No claim register exists.",
    gap: "And a same-working-day clock could not be expressed even with one: every SLA in the hub is in working days, through a step engine shared by ten modules.",
  },
  {
    code: "B.4",
    section: "B",
    block: "B1 · PF / ESIC registration tracker",
    label: "Employee · DOJ · PF details sent · ESIC details sent · Consultant ack. · Closure date · Status",
    targetText: "One row per joiner registered this week",
    kind: "count",
    coverage: "no-table",
    source: "No table.",
    gap: "Seven columns, none of which exists. A small build: one table, one screen, one owner.",
  },
  {
    code: "B.5",
    section: "B",
    block: "B2 · Insurance addition / deletion tracker",
    label: "Employee · Addition/Deletion · DOJ/LWD · Request date · Insurer/TPA ack. · Effective/Closure date · Status",
    targetText: "One row per endorsement this week",
    kind: "count",
    coverage: "no-table",
    source: "No table.",
    gap: "The DOJ and LWD halves already exist (onboarding and exit); the endorsement itself does not.",
  },
  {
    code: "B.6",
    section: "B",
    block: "B3 · Insurance claims tracker",
    label: "Employee · Claim type · Claim date · Intimation date · Current status · Last follow-up · Settlement/Closure · Remarks",
    targetText: "One row per open claim",
    kind: "count",
    coverage: "no-table",
    source: "No table.",
    gap: "The one register on this form with a weekly follow-up clock, and nothing behind it.",
  },

  /* ═══ C · Employee data, HROne & user-ID administration — 10% ═════════════ */
  {
    code: "C.1",
    section: "C",
    block: "Controls",
    label: "Approved employee-master changes",
    targetText: "Within 2 working days",
    kind: "percent",
    coverage: "no-table",
    source: "profiles is edited in Admin → Users; only updated_at moves.",
    gap: "There is no approved-request date to measure two working days from, and no audit of what changed. Both halves would have to be built.",
  },
  {
    code: "C.2",
    section: "C",
    block: "Controls",
    label: "HROne activation for new joiners",
    targetText: "Within 48 hours of DOJ",
    kind: "percent",
    coverage: "no-table",
    source: "HROne — see A.1.",
    gap: "Repeated from section A, where the same clock is asked for.",
  },
  {
    code: "C.3",
    section: "C",
    block: "Controls",
    label: "HROne deactivation and status update for exits",
    targetText: "Within 2 working days of LWD",
    kind: "percent",
    coverage: "no-table",
    source: "HROne.",
    gap: "The hub can hold the LWD (Employee Exit does), but not the HROne side of it.",
  },
  {
    code: "C.4",
    section: "C",
    block: "Controls",
    label: "Email and applicable access deletion request",
    targetText: "Within 2 working days of LWD",
    kind: "percent",
    coverage: "empty-table",
    source: 'fms_exit_clearance_checks — the clearance item "Laptop, email disable, system access, software licences", with an owner and a due date.',
    gap: "Built and unused: fms_exit_cases holds ZERO rows, so not one separation has been run through the module. Nobody has to build anything — somebody has to start using it, and this box fills itself the first week they do.",
  },
  {
    code: "C.5",
    section: "C",
    block: "Controls",
    label: "Audit-trail accuracy",
    targetText: "100%",
    kind: "percent",
    coverage: "empty-table",
    source: "fms_exit_activity — every exit action is stamped with who and when.",
    gap: "Real for the exit side and empty for the same reason as C.4. It says nothing about master changes, which have no audit at all.",
  },
  {
    code: "C.6",
    section: "C",
    block: "Change / exit register",
    label: "Employee · DOJ/LWD · Action or change · HROne status · Email/Access status · Due date · Completion date · Evidence",
    targetText: "One row per change or exit this week",
    kind: "count",
    coverage: "empty-table",
    source: "fms_exit_cases + fms_exit_clearance_checks.",
    gap: "Six of the eight columns exist in Employee Exit and hold no rows; the HROne column never will; the master-change rows have nowhere to come from.",
  },

  /* ═══ D · Office administration & facility management — 10% ═══════════════ */
  /* The section General Purchase answers. */
  {
    code: "D.1",
    section: "D",
    block: "KPIs",
    label: "Requests logged in Orange Hub",
    targetText: "100%",
    kind: "percent",
    coverage: "no-table",
    source: "fms_supplies_requests — but see the gap.",
    gap: "⚠ Unmeasurable FROM INSIDE the hub, by construction. The module can count every request that was logged; a request somebody handled over WhatsApp leaves no row to miss. Only a reconciliation against something outside — a stores register, a vendor bill — could answer this, and the honest form of the box is a judgement.",
  },
  {
    code: "D.2",
    section: "D",
    block: "KPIs",
    label: "Routine requests closed",
    targetText: "Minimum 95% within 3 working days",
    kind: "percent",
    coverage: "live",
    source: "kpi_facts, module office-supplies, row handover — on time ÷ done. The step's configured SLA is exactly 3 working days.",
  },
  {
    code: "D.3",
    section: "D",
    block: "KPIs",
    label: "Avoidable stationery stock-out",
    targetText: "Zero",
    kind: "count",
    coverage: "no-table",
    source: "Nothing tracks stock.",
    gap: "General Purchase tracks REQUESTS, not stock. There is no item-level on-hand quantity, no re-order level and no stock-out event. ⚠ And a zero here must never be read as a pass: \"no stock-out\" and \"nobody records stock-outs\" give the same zero.",
  },
  {
    code: "D.4",
    section: "D",
    block: "Request register",
    label: "Request/Location · Category · Created · Due · Closed · Owner/Vendor · Status",
    targetText: "One row per admin or facility request this week",
    kind: "count",
    coverage: "live",
    source: "fms_supplies_requests — req_no, location, category, submitted_at, the handover due date, delivered_at, the handover owner and the status.",
    gap: "Six of the seven columns are exact. VENDOR is the exception: the module records who handed the item over, not who supplied it — there is no vendor on a request.",
  },

  /* ═══ E · CRM & business support — 5% ═════════════════════════════════════ */
  {
    code: "E.1",
    section: "E",
    block: "KPIs",
    label: "Inward CRM enquiries routed",
    targetText: "100% same working day",
    kind: "percent",
    coverage: "no-table",
    source: "Nothing records an inward enquiry being routed.",
    gap: "⚠ The Leads screen is not this. app_leads is a personal capture log — who I met, which company — keyed to the person who typed it, with no recipient, no routing timestamp and no acknowledgement.",
  },
  {
    code: "E.2",
    section: "E",
    block: "KPIs",
    label: "Complete information and urgency classification",
    targetText: "100%",
    kind: "percent",
    coverage: "no-table",
    source: "No urgency field exists on any enquiry record.",
    gap: "Would come with the register in E.1, not separately.",
  },
  {
    code: "E.3",
    section: "E",
    block: "Enquiry register",
    label: "Enquiry · Received · Sales Coordinator · Routed · Urgency · Ack. · Status",
    targetText: "One row per inward enquiry this week",
    kind: "count",
    coverage: "no-table",
    source: "No table.",
    gap: "Seven columns, none of which app_leads carries.",
  },

  /* ═══ F · Finance, petty cash & office bills — 8% ═════════════════════════ */
  {
    code: "F.1",
    section: "F",
    block: "KPIs",
    label: "Bill verification / support",
    targetText: "100% before submission",
    kind: "percent",
    coverage: "no-table",
    source: "Bills live in Tally, which the hub reads for receivables and nothing else.",
    gap: "There is no bill register in any module. Purchase FMS covers goods purchase orders, not office and utility bills.",
  },
  {
    code: "F.2",
    section: "F",
    block: "KPIs",
    label: "Petty-cash reconciliation",
    targetText: "Updated and reconciled",
    kind: "text",
    coverage: "no-table",
    source: "No petty-cash ledger.",
    gap: "Kept on paper and in Tally. Nothing in the hub touches it.",
  },
  {
    code: "F.3",
    section: "F",
    block: "KPIs",
    label: "Vendor / Finance follow-up",
    targetText: "Tracked to closure",
    kind: "text",
    coverage: "narrative",
    source: "A judgement, and the form states no numeric target.",
  },
  {
    code: "F.4",
    section: "F",
    block: "Bill register",
    label: "Vendor/Bill · Invoice date · Amount · Verified · Submitted · Payment status · Remarks",
    targetText: "One row per bill handled this week",
    kind: "count",
    coverage: "no-table",
    source: "No table.",
    gap: "The payment status exists in Tally; the verification and submission steps this line is about do not exist anywhere.",
  },

  /* ═══ G · Asset management & HROne asset tracking — 7% ════════════════════ */
  {
    code: "G.1",
    section: "G",
    block: "KPIs",
    label: "Asset movements updated",
    targetText: "100%",
    kind: "percent",
    coverage: "no-table",
    source: "fms_asset_assets holds a custodian, not a movement.",
    gap: "custodian_user_id is ONE column; reassigning an asset overwrites it. There is no allocation / transfer / return event and no from-and-to, so a movement cannot be counted, only the current state read.",
  },
  {
    code: "G.2",
    section: "G",
    block: "KPIs",
    label: "Employee acknowledgement",
    targetText: "100% applicable",
    kind: "percent",
    coverage: "no-table",
    source: "Nothing captures an employee acknowledging an asset.",
    gap: "The closest thing in the hub is the Employee Exit clearance tick, which is the RETURN end only and belongs to somebody else.",
  },
  {
    code: "G.3",
    section: "G",
    block: "KPIs",
    label: "Reconciliation",
    targetText: "Complete and traceable",
    kind: "text",
    coverage: "live-partial",
    source: "fms_asset_assets — 40 assets, live since 14-09-2026, with category, location, company and custodian.",
    gap: "⚠ The register is real but the custodians are provisional: 11 of the 17 tracked assets have nobody named and six carry placeholder names lifted from the insurance policies. A completeness figure today measures a half-filled register, not her work.",
  },
  {
    code: "G.4",
    section: "G",
    block: "Movement register",
    label: "Employee · Asset · Movement · Date · HROne updated · Ack. · Status",
    targetText: "One row per asset movement this week",
    kind: "count",
    coverage: "no-table",
    source: "No movement table.",
    gap: "Asset and employee exist; movement, date, acknowledgement and the HROne column do not.",
  },

  /* ═══ HD · Courier & dispatch management — 5% ═════════════════════════════ */
  {
    code: "HD.1",
    section: "HD",
    block: "KPIs",
    label: "Dispatch records",
    targetText: "100% maintained",
    kind: "percent",
    coverage: "no-table",
    source: "No courier register.",
    gap: "⚠ Order to Dispatch is a different dispatch — a customer SALES order from credit check to gate-out. This line is the office courier book: documents, cheques and samples going out by courier. Same word, different register.",
  },
  {
    code: "HD.2",
    section: "HD",
    block: "KPIs",
    label: "Delivery follow-up",
    targetText: "Until closure",
    kind: "percent",
    coverage: "no-table",
    source: "No courier register.",
    gap: "Would come with HD.1.",
  },
  {
    code: "HD.3",
    section: "HD",
    block: "Courier register",
    label: "Dispatch date · Recipient · Material · Vendor · Tracking no. · Delivery · Remarks",
    targetText: "One row per dispatch this week",
    kind: "count",
    coverage: "no-table",
    source: "No table.",
    gap: "Seven columns and a tracking number, none of which the hub holds. One of the smaller builds on this form.",
  },

  /* ═══ I · IT coordination — 5% ════════════════════════════════════════════ */
  {
    code: "I.1",
    section: "I",
    block: "KPIs",
    label: "Complaint logged / escalated",
    targetText: "On receipt",
    kind: "percent",
    coverage: "not-released",
    source: "The Help Desk module, under construction.",
  },
  {
    code: "I.2",
    section: "I",
    block: "KPIs",
    label: "Follow-up",
    targetText: "Daily until resolution / overdue escalation",
    kind: "percent",
    coverage: "not-released",
    source: "The Help Desk module, under construction.",
  },
  {
    code: "I.3",
    section: "I",
    block: "Ticket register",
    label: "Ticket/User · Issue · Logged · Escalated to / date · Due · Closed · Status",
    targetText: "One row per IT complaint this week",
    kind: "count",
    coverage: "not-released",
    source: "The Help Desk module, under construction.",
  },

  /* ═══ J · Orange Hub FMS task management — 15% ════════════════════════════ */
  {
    code: "J.1",
    section: "J",
    block: "KPIs",
    label: "On-time completion",
    targetText: "Minimum 95%",
    kind: "percent",
    coverage: "live",
    source: "kpi_facts, module task-management — on time ÷ done, on each task's own due date.",
  },
  {
    code: "J.2",
    section: "J",
    block: "KPIs",
    label: "Evidence upload",
    targetText: "100% completed tasks",
    kind: "percent",
    coverage: "no-table",
    source: "Nothing counts an attachment against a task.",
    gap: "A task can carry a note; there is no evidence field and nothing that would make a count of one meaningful.",
  },
  {
    code: "J.3",
    section: "J",
    block: "KPIs",
    label: "Overdue tasks",
    targetText: "Reason, revised date and escalation mandatory",
    kind: "count",
    coverage: "live-partial",
    source: "kpi_facts — overdue rows are counted.",
    gap: "The COUNT is exact. The reason, the revised date and the escalation are not fields a task carries, so the three things the form makes mandatory cannot be evidenced.",
  },
  {
    code: "J.4",
    section: "J",
    block: "Task register",
    label: "Task · KRA bucket · Assigned · Due · Closed · Evidence · Status/Escalation",
    targetText: "One row per task this week",
    kind: "count",
    coverage: "live-partial",
    source: "kpi_facts + the tasks table — title, assignment, due date and closure.",
    gap: 'Four of the seven columns are exact. "KRA bucket" is the interesting miss: this form wants every task filed against a KRA, and a task has no such field — the same gap Saloni\'s sheet hit from the other end. Evidence is J.2. ⚠ Read the closure dates with the module\'s two traps in mind: a bulk-closed task carries the sweep\'s timestamp, and a recurring task exists a day before it is due.',
  },

  /* ═══ K · Attendance, reporting & training compliance — 5% ════════════════ */
  {
    code: "K.1",
    section: "K",
    block: "Parameters",
    label: "Attendance",
    targetText: "Minimum 75%",
    kind: "percent",
    coverage: "no-table",
    source: "Biometric, outside the hub.",
    gap: "No attendance or leave table of any kind. It would be an integration, not a screen.",
  },
  {
    code: "K.2",
    section: "K",
    block: "Parameters",
    label: "Assigned reports",
    targetText: "100% on time",
    kind: "percent",
    coverage: "no-table",
    source: "Nothing records a report being submitted.",
    gap: "⚠ Circular on this page: THIS report saves nothing, so it cannot evidence its own submission. Making the weekly report a record would fill this box and is the open question already with HR.",
  },
  {
    code: "K.3",
    section: "K",
    block: "Parameters",
    label: "Mandatory training",
    targetText: "100% within assigned timeline",
    kind: "percent",
    coverage: "empty-table",
    source: "fms_ld_mandatory_programs + fms_ld_nominations + fms_ld_attendance — Learning & Development, live since 23-09-2026.",
    gap: "Two mandatory programs are defined and no nomination names her. Somebody has to say which programs are hers; after that this box fills itself, including the timeline.",
  },

  /* ═══ L · Behaviour, discipline & cross-departmental coordination — 5% ════ */
  {
    code: "L.1",
    section: "L",
    block: "Parameters",
    label: "Disciplinary / policy violation",
    targetText: "Zero substantiated cases",
    kind: "count",
    coverage: "narrative",
    source: "A judgement, by design.",
    gap: "⚠ A zero must never be read as a pass: nothing records violations, so \"none happened\" and \"none are recorded\" look identical. fms_hr_grievances is the nearest real record and answers a different question.",
  },
  {
    code: "L.2",
    section: "L",
    block: "Parameters",
    label: "Cross-functional coordination",
    targetText: "Within applicable SLA",
    kind: "text",
    coverage: "narrative",
    source: "A judgement. The form names no single SLA to measure against.",
  },
  {
    code: "L.3",
    section: "L",
    block: "Parameters",
    label: "Avoidable escalation",
    targetText: "Zero justified escalation",
    kind: "count",
    coverage: "narrative",
    source: "A judgement, by design.",
  },

  /* ═══ M · Risks, pending actions & next-week plan ═════════════════════════ */
  {
    code: "M.1",
    section: "M",
    block: "M1 · Risks and escalations",
    label: "Area · Risk/Issue · Impact · Escalated to · Action · Target date · Status",
    targetText: "One row per open risk",
    kind: "text",
    coverage: "narrative",
    source: "Written by the person filing the report.",
  },
  {
    code: "M.2",
    section: "M",
    block: "M2 · Next-week priorities",
    label: "Priority / Deliverable · KRA · Target date · Support required",
    targetText: "Six numbered lines",
    kind: "text",
    coverage: "narrative",
    source: "Written by the person filing the report.",
  },

  /* ═══ N · Final KPI validation & sign-off ═════════════════════════════════ */
  {
    code: "N.1",
    section: "N",
    block: "Validation",
    label: "Verified weightage, per KRA",
    targetText: "Twelve KRAs, total 100%",
    kind: "percent",
    coverage: "live",
    source: "Her framework sheet, which the page checks adds to 100 before it renders anything.",
  },
  {
    code: "N.2",
    section: "N",
    block: "Sign-off",
    label: "Prepared by · Reviewed by · Approved by",
    targetText: "Dharmistha Prajapati · Assistant Manager / HR-Admin Head · Management",
    kind: "text",
    coverage: "narrative",
    source: "Signatures on a printed page.",
    gap: "⚠ Nothing here is signed or stored. If HR want a signed weekly record, that is a table, RLS and an approval — not a tweak to this page.",
  },
];

export const dharmisthaWeeklyForm: ReportForm = {
  id: "dharmistha-weekly-2026",
  role: "Executive - HR & Admin",
  source:
    "ORANGE O TEC · FINAL UPDATED WEEKLY REVIEW REPORT · Executive - HR & Admin | Insurance, HROne ID and Exit Controls (Dharmistha_Prajapati_Final_Updated_Weekly_Report_Insurance_ID_2026.docx)",
  sections: [
    { code: "H", title: "Report header", note: "Who, which week, and how the week went overall." },
    { code: "DASH", title: "Executive KPI dashboard", note: "The twelve KRAs and their weights, one status line each." },
    { code: "A", title: "A · New joiner onboarding & employee master management — 15%", note: "Onboarding is measurable; HROne is not." },
    { code: "B", title: "B · Compliance, registration & insurance — 10%", note: "Nothing in the hub holds PF, ESIC or employee insurance." },
    { code: "C", title: "C · Employee data, HROne & user-ID administration — 10%", note: "Employee Exit covers the exit half and has never been used." },
    { code: "D", title: "D · Office administration & facility management — 10%", note: "General Purchase. The section the hub fills." },
    { code: "E", title: "E · CRM & business support — 5%", note: "The Leads screen is a personal capture log, not an enquiry router." },
    { code: "F", title: "F · Finance, petty cash & office bills — 8%", note: "Tally's ground, not the hub's." },
    { code: "G", title: "G · Asset management & HROne asset tracking — 7%", note: "The register holds a state; this section asks for movements." },
    { code: "HD", title: "H · Courier & dispatch management — 5%", note: "The office courier book. Order to Dispatch is a different dispatch." },
    { code: "I", title: "I · IT coordination — 5%", note: "Waiting on the Help Desk, which is under construction." },
    { code: "J", title: "J · Orange Hub FMS task management — 15%", note: "Task Management. The other section the hub fills." },
    { code: "K", title: "K · Attendance, reporting & training compliance — 5%", note: "One of the three is measurable today." },
    { code: "L", title: "L · Behaviour, discipline & cross-departmental coordination — 5%", note: "Judgement, by design." },
    { code: "M", title: "M · Risks, pending actions & next-week plan", note: "Written by the person filing the report." },
    { code: "N", title: "N · Final KPI validation & sign-off", note: "The weights, checked; the signatures, on paper." },
  ],
  fields,
};
